package com.bornfire.brrs.entities;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;
import org.springframework.format.annotation.DateTimeFormat;


@Entity
@Table(name = "BRRS_M_NOSVOS_P5_ARCHIVAL_DETAIL")
@IdClass(BRRS_NOSVOS_Summary_PK.class)
public class BrrsMNosvosP5ArchivalDetail {
	@Id
	@Column(name = "REPORT_DATE")
	private Date REPORT_DATE;
	@Column(name = "REPORT_VERSION")
	private String REPORT_VERSION;
	@Column(name = "REPORT_FREQUENCY")
	private String REPORT_FREQUENCY;
	@Column(name = "REPORT_CODE")
	private String REPORT_CODE;
	@Column(name = "REPORT_DESC")
	private String REPORT_DESC;
	@Column(name = "ENTITY_FLG")
	private String ENTITY_FLG;
	@Column(name = "MODIFY_FLG")
	private String MODIFY_FLG;
	@Column(name = "DEL_FLG")
	private String DEL_FLG;
	
	private String R1_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R1_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R1_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R1_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R1_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R1_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R1_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R2_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R2_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R2_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R2_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R2_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R2_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R2_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R3_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R3_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R3_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R3_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R3_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R3_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R3_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R4_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R4_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R4_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R4_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R4_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R4_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R4_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R5_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R5_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R5_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R5_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R5_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R5_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R5_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R6_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R6_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R6_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R6_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R6_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R6_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R6_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R7_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R7_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R7_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R7_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R7_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R7_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R7_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R8_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R8_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R8_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R8_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R8_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R8_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R8_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R9_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R9_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R9_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R9_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R9_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R9_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R9_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R10_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R10_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R10_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R10_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R10_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R10_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R10_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
private String R11_DUE_FROM_DOMESTIC_NAME_OF_BANK;
private BigDecimal R11_DUE_FROM_DOMESTIC_ACCT_TYPE;
private BigDecimal R11_DUE_FROM_DOMESTIC_PURPOSE;
private BigDecimal R11_DUE_FROM_DOMESTIC_AMOUNT;
private BigDecimal R11_DUE_FROM_DOMESTIC_RISK_WEIGHT;
private String R11_DUE_FROM_DOMESTIC_CURRENCY;
private BigDecimal R11_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;

private String R1_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R1_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R1_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R1_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R1_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R1_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
private String R2_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R2_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R2_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R2_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R2_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R2_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
private String R3_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R3_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R3_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R3_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R3_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R3_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
private String R4_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R4_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R4_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R4_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R4_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R4_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
private String R5_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R5_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R5_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R5_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R5_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R5_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
private String R6_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R6_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R6_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R6_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R6_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R6_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
private String R7_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R7_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R7_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R7_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R7_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R7_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
private String R8_DUE_TO_DOMESTIC_NAME_OF_BANK;
private BigDecimal R8_DUE_TO_DOMESTIC_ACCT_TYPE;
private BigDecimal R8_DUE_TO_DOMESTIC_PURPOSE;
private BigDecimal R8_DUE_TO_DOMESTIC_AMOUNT;
private BigDecimal R8_DUE_TO_DOMESTIC_RISK_WEIGHT;
private BigDecimal R8_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
public Date getREPORT_DATE() {
	return REPORT_DATE;
}
public void setREPORT_DATE(Date rEPORT_DATE) {
	REPORT_DATE = rEPORT_DATE;
}
public String getREPORT_VERSION() {
	return REPORT_VERSION;
}
public void setREPORT_VERSION(String rEPORT_VERSION) {
	REPORT_VERSION = rEPORT_VERSION;
}
public String getREPORT_FREQUENCY() {
	return REPORT_FREQUENCY;
}
public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
	REPORT_FREQUENCY = rEPORT_FREQUENCY;
}
public String getREPORT_CODE() {
	return REPORT_CODE;
}
public void setREPORT_CODE(String rEPORT_CODE) {
	REPORT_CODE = rEPORT_CODE;
}
public String getREPORT_DESC() {
	return REPORT_DESC;
}
public void setREPORT_DESC(String rEPORT_DESC) {
	REPORT_DESC = rEPORT_DESC;
}
public String getENTITY_FLG() {
	return ENTITY_FLG;
}
public void setENTITY_FLG(String eNTITY_FLG) {
	ENTITY_FLG = eNTITY_FLG;
}
public String getMODIFY_FLG() {
	return MODIFY_FLG;
}
public void setMODIFY_FLG(String mODIFY_FLG) {
	MODIFY_FLG = mODIFY_FLG;
}
public String getDEL_FLG() {
	return DEL_FLG;
}
public void setDEL_FLG(String dEL_FLG) {
	DEL_FLG = dEL_FLG;
}
public String getR1_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R1_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR1_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r1_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R1_DUE_FROM_DOMESTIC_NAME_OF_BANK = r1_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR1_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R1_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR1_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r1_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R1_DUE_FROM_DOMESTIC_ACCT_TYPE = r1_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR1_DUE_FROM_DOMESTIC_PURPOSE() {
	return R1_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR1_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r1_DUE_FROM_DOMESTIC_PURPOSE) {
	R1_DUE_FROM_DOMESTIC_PURPOSE = r1_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR1_DUE_FROM_DOMESTIC_AMOUNT() {
	return R1_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR1_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r1_DUE_FROM_DOMESTIC_AMOUNT) {
	R1_DUE_FROM_DOMESTIC_AMOUNT = r1_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR1_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R1_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR1_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r1_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R1_DUE_FROM_DOMESTIC_RISK_WEIGHT = r1_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR1_DUE_FROM_DOMESTIC_CURRENCY() {
	return R1_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR1_DUE_FROM_DOMESTIC_CURRENCY(String r1_DUE_FROM_DOMESTIC_CURRENCY) {
	R1_DUE_FROM_DOMESTIC_CURRENCY = r1_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR1_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R1_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR1_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r1_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R1_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r1_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR2_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R2_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR2_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r2_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R2_DUE_FROM_DOMESTIC_NAME_OF_BANK = r2_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR2_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R2_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR2_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r2_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R2_DUE_FROM_DOMESTIC_ACCT_TYPE = r2_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR2_DUE_FROM_DOMESTIC_PURPOSE() {
	return R2_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR2_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r2_DUE_FROM_DOMESTIC_PURPOSE) {
	R2_DUE_FROM_DOMESTIC_PURPOSE = r2_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR2_DUE_FROM_DOMESTIC_AMOUNT() {
	return R2_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR2_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r2_DUE_FROM_DOMESTIC_AMOUNT) {
	R2_DUE_FROM_DOMESTIC_AMOUNT = r2_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR2_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R2_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR2_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r2_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R2_DUE_FROM_DOMESTIC_RISK_WEIGHT = r2_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR2_DUE_FROM_DOMESTIC_CURRENCY() {
	return R2_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR2_DUE_FROM_DOMESTIC_CURRENCY(String r2_DUE_FROM_DOMESTIC_CURRENCY) {
	R2_DUE_FROM_DOMESTIC_CURRENCY = r2_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR2_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R2_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR2_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r2_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R2_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r2_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR3_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R3_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR3_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r3_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R3_DUE_FROM_DOMESTIC_NAME_OF_BANK = r3_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR3_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R3_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR3_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r3_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R3_DUE_FROM_DOMESTIC_ACCT_TYPE = r3_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR3_DUE_FROM_DOMESTIC_PURPOSE() {
	return R3_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR3_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r3_DUE_FROM_DOMESTIC_PURPOSE) {
	R3_DUE_FROM_DOMESTIC_PURPOSE = r3_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR3_DUE_FROM_DOMESTIC_AMOUNT() {
	return R3_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR3_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r3_DUE_FROM_DOMESTIC_AMOUNT) {
	R3_DUE_FROM_DOMESTIC_AMOUNT = r3_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR3_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R3_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR3_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r3_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R3_DUE_FROM_DOMESTIC_RISK_WEIGHT = r3_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR3_DUE_FROM_DOMESTIC_CURRENCY() {
	return R3_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR3_DUE_FROM_DOMESTIC_CURRENCY(String r3_DUE_FROM_DOMESTIC_CURRENCY) {
	R3_DUE_FROM_DOMESTIC_CURRENCY = r3_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR3_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R3_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR3_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r3_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R3_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r3_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR4_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R4_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR4_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r4_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R4_DUE_FROM_DOMESTIC_NAME_OF_BANK = r4_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR4_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R4_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR4_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r4_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R4_DUE_FROM_DOMESTIC_ACCT_TYPE = r4_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR4_DUE_FROM_DOMESTIC_PURPOSE() {
	return R4_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR4_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r4_DUE_FROM_DOMESTIC_PURPOSE) {
	R4_DUE_FROM_DOMESTIC_PURPOSE = r4_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR4_DUE_FROM_DOMESTIC_AMOUNT() {
	return R4_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR4_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r4_DUE_FROM_DOMESTIC_AMOUNT) {
	R4_DUE_FROM_DOMESTIC_AMOUNT = r4_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR4_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R4_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR4_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r4_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R4_DUE_FROM_DOMESTIC_RISK_WEIGHT = r4_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR4_DUE_FROM_DOMESTIC_CURRENCY() {
	return R4_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR4_DUE_FROM_DOMESTIC_CURRENCY(String r4_DUE_FROM_DOMESTIC_CURRENCY) {
	R4_DUE_FROM_DOMESTIC_CURRENCY = r4_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR4_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R4_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR4_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r4_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R4_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r4_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR5_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R5_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR5_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r5_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R5_DUE_FROM_DOMESTIC_NAME_OF_BANK = r5_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR5_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R5_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR5_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r5_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R5_DUE_FROM_DOMESTIC_ACCT_TYPE = r5_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR5_DUE_FROM_DOMESTIC_PURPOSE() {
	return R5_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR5_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r5_DUE_FROM_DOMESTIC_PURPOSE) {
	R5_DUE_FROM_DOMESTIC_PURPOSE = r5_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR5_DUE_FROM_DOMESTIC_AMOUNT() {
	return R5_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR5_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r5_DUE_FROM_DOMESTIC_AMOUNT) {
	R5_DUE_FROM_DOMESTIC_AMOUNT = r5_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR5_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R5_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR5_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r5_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R5_DUE_FROM_DOMESTIC_RISK_WEIGHT = r5_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR5_DUE_FROM_DOMESTIC_CURRENCY() {
	return R5_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR5_DUE_FROM_DOMESTIC_CURRENCY(String r5_DUE_FROM_DOMESTIC_CURRENCY) {
	R5_DUE_FROM_DOMESTIC_CURRENCY = r5_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR5_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R5_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR5_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r5_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R5_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r5_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR6_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R6_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR6_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r6_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R6_DUE_FROM_DOMESTIC_NAME_OF_BANK = r6_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR6_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R6_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR6_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r6_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R6_DUE_FROM_DOMESTIC_ACCT_TYPE = r6_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR6_DUE_FROM_DOMESTIC_PURPOSE() {
	return R6_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR6_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r6_DUE_FROM_DOMESTIC_PURPOSE) {
	R6_DUE_FROM_DOMESTIC_PURPOSE = r6_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR6_DUE_FROM_DOMESTIC_AMOUNT() {
	return R6_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR6_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r6_DUE_FROM_DOMESTIC_AMOUNT) {
	R6_DUE_FROM_DOMESTIC_AMOUNT = r6_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR6_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R6_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR6_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r6_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R6_DUE_FROM_DOMESTIC_RISK_WEIGHT = r6_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR6_DUE_FROM_DOMESTIC_CURRENCY() {
	return R6_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR6_DUE_FROM_DOMESTIC_CURRENCY(String r6_DUE_FROM_DOMESTIC_CURRENCY) {
	R6_DUE_FROM_DOMESTIC_CURRENCY = r6_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR6_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R6_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR6_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r6_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R6_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r6_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR7_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R7_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR7_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r7_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R7_DUE_FROM_DOMESTIC_NAME_OF_BANK = r7_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR7_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R7_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR7_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r7_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R7_DUE_FROM_DOMESTIC_ACCT_TYPE = r7_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR7_DUE_FROM_DOMESTIC_PURPOSE() {
	return R7_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR7_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r7_DUE_FROM_DOMESTIC_PURPOSE) {
	R7_DUE_FROM_DOMESTIC_PURPOSE = r7_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR7_DUE_FROM_DOMESTIC_AMOUNT() {
	return R7_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR7_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r7_DUE_FROM_DOMESTIC_AMOUNT) {
	R7_DUE_FROM_DOMESTIC_AMOUNT = r7_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR7_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R7_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR7_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r7_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R7_DUE_FROM_DOMESTIC_RISK_WEIGHT = r7_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR7_DUE_FROM_DOMESTIC_CURRENCY() {
	return R7_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR7_DUE_FROM_DOMESTIC_CURRENCY(String r7_DUE_FROM_DOMESTIC_CURRENCY) {
	R7_DUE_FROM_DOMESTIC_CURRENCY = r7_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR7_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R7_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR7_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r7_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R7_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r7_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR8_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R8_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR8_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r8_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R8_DUE_FROM_DOMESTIC_NAME_OF_BANK = r8_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR8_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R8_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR8_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r8_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R8_DUE_FROM_DOMESTIC_ACCT_TYPE = r8_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR8_DUE_FROM_DOMESTIC_PURPOSE() {
	return R8_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR8_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r8_DUE_FROM_DOMESTIC_PURPOSE) {
	R8_DUE_FROM_DOMESTIC_PURPOSE = r8_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR8_DUE_FROM_DOMESTIC_AMOUNT() {
	return R8_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR8_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r8_DUE_FROM_DOMESTIC_AMOUNT) {
	R8_DUE_FROM_DOMESTIC_AMOUNT = r8_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR8_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R8_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR8_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r8_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R8_DUE_FROM_DOMESTIC_RISK_WEIGHT = r8_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR8_DUE_FROM_DOMESTIC_CURRENCY() {
	return R8_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR8_DUE_FROM_DOMESTIC_CURRENCY(String r8_DUE_FROM_DOMESTIC_CURRENCY) {
	R8_DUE_FROM_DOMESTIC_CURRENCY = r8_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR8_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R8_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR8_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r8_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R8_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r8_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR9_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R9_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR9_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r9_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R9_DUE_FROM_DOMESTIC_NAME_OF_BANK = r9_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR9_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R9_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR9_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r9_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R9_DUE_FROM_DOMESTIC_ACCT_TYPE = r9_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR9_DUE_FROM_DOMESTIC_PURPOSE() {
	return R9_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR9_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r9_DUE_FROM_DOMESTIC_PURPOSE) {
	R9_DUE_FROM_DOMESTIC_PURPOSE = r9_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR9_DUE_FROM_DOMESTIC_AMOUNT() {
	return R9_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR9_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r9_DUE_FROM_DOMESTIC_AMOUNT) {
	R9_DUE_FROM_DOMESTIC_AMOUNT = r9_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR9_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R9_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR9_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r9_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R9_DUE_FROM_DOMESTIC_RISK_WEIGHT = r9_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR9_DUE_FROM_DOMESTIC_CURRENCY() {
	return R9_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR9_DUE_FROM_DOMESTIC_CURRENCY(String r9_DUE_FROM_DOMESTIC_CURRENCY) {
	R9_DUE_FROM_DOMESTIC_CURRENCY = r9_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR9_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R9_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR9_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r9_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R9_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r9_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR10_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R10_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR10_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r10_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R10_DUE_FROM_DOMESTIC_NAME_OF_BANK = r10_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR10_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R10_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR10_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r10_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R10_DUE_FROM_DOMESTIC_ACCT_TYPE = r10_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR10_DUE_FROM_DOMESTIC_PURPOSE() {
	return R10_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR10_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r10_DUE_FROM_DOMESTIC_PURPOSE) {
	R10_DUE_FROM_DOMESTIC_PURPOSE = r10_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR10_DUE_FROM_DOMESTIC_AMOUNT() {
	return R10_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR10_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r10_DUE_FROM_DOMESTIC_AMOUNT) {
	R10_DUE_FROM_DOMESTIC_AMOUNT = r10_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR10_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R10_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR10_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r10_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R10_DUE_FROM_DOMESTIC_RISK_WEIGHT = r10_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR10_DUE_FROM_DOMESTIC_CURRENCY() {
	return R10_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR10_DUE_FROM_DOMESTIC_CURRENCY(String r10_DUE_FROM_DOMESTIC_CURRENCY) {
	R10_DUE_FROM_DOMESTIC_CURRENCY = r10_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR10_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R10_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR10_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r10_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R10_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r10_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR11_DUE_FROM_DOMESTIC_NAME_OF_BANK() {
	return R11_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public void setR11_DUE_FROM_DOMESTIC_NAME_OF_BANK(String r11_DUE_FROM_DOMESTIC_NAME_OF_BANK) {
	R11_DUE_FROM_DOMESTIC_NAME_OF_BANK = r11_DUE_FROM_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR11_DUE_FROM_DOMESTIC_ACCT_TYPE() {
	return R11_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public void setR11_DUE_FROM_DOMESTIC_ACCT_TYPE(BigDecimal r11_DUE_FROM_DOMESTIC_ACCT_TYPE) {
	R11_DUE_FROM_DOMESTIC_ACCT_TYPE = r11_DUE_FROM_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR11_DUE_FROM_DOMESTIC_PURPOSE() {
	return R11_DUE_FROM_DOMESTIC_PURPOSE;
}
public void setR11_DUE_FROM_DOMESTIC_PURPOSE(BigDecimal r11_DUE_FROM_DOMESTIC_PURPOSE) {
	R11_DUE_FROM_DOMESTIC_PURPOSE = r11_DUE_FROM_DOMESTIC_PURPOSE;
}
public BigDecimal getR11_DUE_FROM_DOMESTIC_AMOUNT() {
	return R11_DUE_FROM_DOMESTIC_AMOUNT;
}
public void setR11_DUE_FROM_DOMESTIC_AMOUNT(BigDecimal r11_DUE_FROM_DOMESTIC_AMOUNT) {
	R11_DUE_FROM_DOMESTIC_AMOUNT = r11_DUE_FROM_DOMESTIC_AMOUNT;
}
public BigDecimal getR11_DUE_FROM_DOMESTIC_RISK_WEIGHT() {
	return R11_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public void setR11_DUE_FROM_DOMESTIC_RISK_WEIGHT(BigDecimal r11_DUE_FROM_DOMESTIC_RISK_WEIGHT) {
	R11_DUE_FROM_DOMESTIC_RISK_WEIGHT = r11_DUE_FROM_DOMESTIC_RISK_WEIGHT;
}
public String getR11_DUE_FROM_DOMESTIC_CURRENCY() {
	return R11_DUE_FROM_DOMESTIC_CURRENCY;
}
public void setR11_DUE_FROM_DOMESTIC_CURRENCY(String r11_DUE_FROM_DOMESTIC_CURRENCY) {
	R11_DUE_FROM_DOMESTIC_CURRENCY = r11_DUE_FROM_DOMESTIC_CURRENCY;
}
public BigDecimal getR11_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT() {
	return R11_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR11_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r11_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT) {
	R11_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT = r11_DUE_FROM_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR1_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R1_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR1_DUE_TO_DOMESTIC_NAME_OF_BANK(String r1_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R1_DUE_TO_DOMESTIC_NAME_OF_BANK = r1_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR1_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R1_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR1_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r1_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R1_DUE_TO_DOMESTIC_ACCT_TYPE = r1_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR1_DUE_TO_DOMESTIC_PURPOSE() {
	return R1_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR1_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r1_DUE_TO_DOMESTIC_PURPOSE) {
	R1_DUE_TO_DOMESTIC_PURPOSE = r1_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR1_DUE_TO_DOMESTIC_AMOUNT() {
	return R1_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR1_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r1_DUE_TO_DOMESTIC_AMOUNT) {
	R1_DUE_TO_DOMESTIC_AMOUNT = r1_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR1_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R1_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR1_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r1_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R1_DUE_TO_DOMESTIC_RISK_WEIGHT = r1_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR1_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R1_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR1_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r1_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R1_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r1_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR2_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R2_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR2_DUE_TO_DOMESTIC_NAME_OF_BANK(String r2_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R2_DUE_TO_DOMESTIC_NAME_OF_BANK = r2_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR2_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R2_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR2_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r2_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R2_DUE_TO_DOMESTIC_ACCT_TYPE = r2_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR2_DUE_TO_DOMESTIC_PURPOSE() {
	return R2_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR2_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r2_DUE_TO_DOMESTIC_PURPOSE) {
	R2_DUE_TO_DOMESTIC_PURPOSE = r2_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR2_DUE_TO_DOMESTIC_AMOUNT() {
	return R2_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR2_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r2_DUE_TO_DOMESTIC_AMOUNT) {
	R2_DUE_TO_DOMESTIC_AMOUNT = r2_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR2_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R2_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR2_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r2_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R2_DUE_TO_DOMESTIC_RISK_WEIGHT = r2_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR2_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R2_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR2_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r2_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R2_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r2_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR3_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R3_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR3_DUE_TO_DOMESTIC_NAME_OF_BANK(String r3_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R3_DUE_TO_DOMESTIC_NAME_OF_BANK = r3_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR3_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R3_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR3_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r3_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R3_DUE_TO_DOMESTIC_ACCT_TYPE = r3_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR3_DUE_TO_DOMESTIC_PURPOSE() {
	return R3_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR3_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r3_DUE_TO_DOMESTIC_PURPOSE) {
	R3_DUE_TO_DOMESTIC_PURPOSE = r3_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR3_DUE_TO_DOMESTIC_AMOUNT() {
	return R3_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR3_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r3_DUE_TO_DOMESTIC_AMOUNT) {
	R3_DUE_TO_DOMESTIC_AMOUNT = r3_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR3_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R3_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR3_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r3_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R3_DUE_TO_DOMESTIC_RISK_WEIGHT = r3_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR3_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R3_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR3_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r3_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R3_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r3_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR4_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R4_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR4_DUE_TO_DOMESTIC_NAME_OF_BANK(String r4_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R4_DUE_TO_DOMESTIC_NAME_OF_BANK = r4_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR4_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R4_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR4_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r4_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R4_DUE_TO_DOMESTIC_ACCT_TYPE = r4_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR4_DUE_TO_DOMESTIC_PURPOSE() {
	return R4_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR4_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r4_DUE_TO_DOMESTIC_PURPOSE) {
	R4_DUE_TO_DOMESTIC_PURPOSE = r4_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR4_DUE_TO_DOMESTIC_AMOUNT() {
	return R4_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR4_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r4_DUE_TO_DOMESTIC_AMOUNT) {
	R4_DUE_TO_DOMESTIC_AMOUNT = r4_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR4_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R4_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR4_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r4_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R4_DUE_TO_DOMESTIC_RISK_WEIGHT = r4_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR4_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R4_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR4_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r4_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R4_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r4_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR5_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R5_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR5_DUE_TO_DOMESTIC_NAME_OF_BANK(String r5_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R5_DUE_TO_DOMESTIC_NAME_OF_BANK = r5_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR5_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R5_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR5_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r5_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R5_DUE_TO_DOMESTIC_ACCT_TYPE = r5_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR5_DUE_TO_DOMESTIC_PURPOSE() {
	return R5_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR5_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r5_DUE_TO_DOMESTIC_PURPOSE) {
	R5_DUE_TO_DOMESTIC_PURPOSE = r5_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR5_DUE_TO_DOMESTIC_AMOUNT() {
	return R5_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR5_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r5_DUE_TO_DOMESTIC_AMOUNT) {
	R5_DUE_TO_DOMESTIC_AMOUNT = r5_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR5_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R5_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR5_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r5_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R5_DUE_TO_DOMESTIC_RISK_WEIGHT = r5_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR5_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R5_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR5_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r5_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R5_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r5_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR6_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R6_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR6_DUE_TO_DOMESTIC_NAME_OF_BANK(String r6_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R6_DUE_TO_DOMESTIC_NAME_OF_BANK = r6_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR6_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R6_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR6_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r6_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R6_DUE_TO_DOMESTIC_ACCT_TYPE = r6_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR6_DUE_TO_DOMESTIC_PURPOSE() {
	return R6_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR6_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r6_DUE_TO_DOMESTIC_PURPOSE) {
	R6_DUE_TO_DOMESTIC_PURPOSE = r6_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR6_DUE_TO_DOMESTIC_AMOUNT() {
	return R6_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR6_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r6_DUE_TO_DOMESTIC_AMOUNT) {
	R6_DUE_TO_DOMESTIC_AMOUNT = r6_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR6_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R6_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR6_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r6_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R6_DUE_TO_DOMESTIC_RISK_WEIGHT = r6_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR6_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R6_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR6_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r6_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R6_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r6_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR7_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R7_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR7_DUE_TO_DOMESTIC_NAME_OF_BANK(String r7_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R7_DUE_TO_DOMESTIC_NAME_OF_BANK = r7_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR7_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R7_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR7_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r7_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R7_DUE_TO_DOMESTIC_ACCT_TYPE = r7_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR7_DUE_TO_DOMESTIC_PURPOSE() {
	return R7_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR7_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r7_DUE_TO_DOMESTIC_PURPOSE) {
	R7_DUE_TO_DOMESTIC_PURPOSE = r7_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR7_DUE_TO_DOMESTIC_AMOUNT() {
	return R7_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR7_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r7_DUE_TO_DOMESTIC_AMOUNT) {
	R7_DUE_TO_DOMESTIC_AMOUNT = r7_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR7_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R7_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR7_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r7_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R7_DUE_TO_DOMESTIC_RISK_WEIGHT = r7_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR7_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R7_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR7_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r7_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R7_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r7_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public String getR8_DUE_TO_DOMESTIC_NAME_OF_BANK() {
	return R8_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public void setR8_DUE_TO_DOMESTIC_NAME_OF_BANK(String r8_DUE_TO_DOMESTIC_NAME_OF_BANK) {
	R8_DUE_TO_DOMESTIC_NAME_OF_BANK = r8_DUE_TO_DOMESTIC_NAME_OF_BANK;
}
public BigDecimal getR8_DUE_TO_DOMESTIC_ACCT_TYPE() {
	return R8_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public void setR8_DUE_TO_DOMESTIC_ACCT_TYPE(BigDecimal r8_DUE_TO_DOMESTIC_ACCT_TYPE) {
	R8_DUE_TO_DOMESTIC_ACCT_TYPE = r8_DUE_TO_DOMESTIC_ACCT_TYPE;
}
public BigDecimal getR8_DUE_TO_DOMESTIC_PURPOSE() {
	return R8_DUE_TO_DOMESTIC_PURPOSE;
}
public void setR8_DUE_TO_DOMESTIC_PURPOSE(BigDecimal r8_DUE_TO_DOMESTIC_PURPOSE) {
	R8_DUE_TO_DOMESTIC_PURPOSE = r8_DUE_TO_DOMESTIC_PURPOSE;
}
public BigDecimal getR8_DUE_TO_DOMESTIC_AMOUNT() {
	return R8_DUE_TO_DOMESTIC_AMOUNT;
}
public void setR8_DUE_TO_DOMESTIC_AMOUNT(BigDecimal r8_DUE_TO_DOMESTIC_AMOUNT) {
	R8_DUE_TO_DOMESTIC_AMOUNT = r8_DUE_TO_DOMESTIC_AMOUNT;
}
public BigDecimal getR8_DUE_TO_DOMESTIC_RISK_WEIGHT() {
	return R8_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public void setR8_DUE_TO_DOMESTIC_RISK_WEIGHT(BigDecimal r8_DUE_TO_DOMESTIC_RISK_WEIGHT) {
	R8_DUE_TO_DOMESTIC_RISK_WEIGHT = r8_DUE_TO_DOMESTIC_RISK_WEIGHT;
}
public BigDecimal getR8_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT() {
	return R8_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}
public void setR8_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT(BigDecimal r8_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT) {
	R8_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT = r8_DUE_TO_DOMESTIC_RISK_WEIGHT_AMT;
}



}