package com.bornfire.brrs.entities;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "BRRS_M_GP_SUMMARYTABLE")
public class M_GP_Summary_Entity {
	private String R11_PRODUCT;
	private BigDecimal R11_STAGE1_PROVISIONS;
	private BigDecimal R11_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R11_TOTAL_GENERAL_PROVISIONS;

	private String R12_PRODUCT;
	private BigDecimal R12_STAGE1_PROVISIONS;
	private BigDecimal R12_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R12_TOTAL_GENERAL_PROVISIONS;

	private String R13_PRODUCT;
	private BigDecimal R13_STAGE1_PROVISIONS;
	private BigDecimal R13_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R13_TOTAL_GENERAL_PROVISIONS;

	private String R14_PRODUCT;
	private BigDecimal R14_STAGE1_PROVISIONS;
	private BigDecimal R14_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R14_TOTAL_GENERAL_PROVISIONS;

	private String R15_PRODUCT;
	private BigDecimal R15_STAGE1_PROVISIONS;
	private BigDecimal R15_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R15_TOTAL_GENERAL_PROVISIONS;

	private String R16_PRODUCT;
	private BigDecimal R16_STAGE1_PROVISIONS;
	private BigDecimal R16_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R16_TOTAL_GENERAL_PROVISIONS;

	private String R17_PRODUCT;
	private BigDecimal R17_STAGE1_PROVISIONS;
	private BigDecimal R17_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R17_TOTAL_GENERAL_PROVISIONS;

	private String R18_PRODUCT;
	private BigDecimal R18_STAGE1_PROVISIONS;
	private BigDecimal R18_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R18_TOTAL_GENERAL_PROVISIONS;

	private String R19_PRODUCT;
	private BigDecimal R19_STAGE1_PROVISIONS;
	private BigDecimal R19_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R19_TOTAL_GENERAL_PROVISIONS;

	private String R20_PRODUCT;
	private BigDecimal R20_STAGE1_PROVISIONS;
	private BigDecimal R20_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R20_TOTAL_GENERAL_PROVISIONS;

	private String R21_PRODUCT;
	private BigDecimal R21_STAGE1_PROVISIONS;
	private BigDecimal R21_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R21_TOTAL_GENERAL_PROVISIONS;

	private String R22_PRODUCT;
	private BigDecimal R22_STAGE1_PROVISIONS;
	private BigDecimal R22_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R22_TOTAL_GENERAL_PROVISIONS;

	private String R23_PRODUCT;
	private BigDecimal R23_STAGE1_PROVISIONS;
	private BigDecimal R23_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R23_TOTAL_GENERAL_PROVISIONS;

	private String R24_PRODUCT;
	private BigDecimal R24_STAGE1_PROVISIONS;
	private BigDecimal R24_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R24_TOTAL_GENERAL_PROVISIONS;

	private String R25_PRODUCT;
	private BigDecimal R25_STAGE1_PROVISIONS;
	private BigDecimal R25_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R25_TOTAL_GENERAL_PROVISIONS;

	private String R26_PRODUCT;
	private BigDecimal R26_STAGE1_PROVISIONS;
	private BigDecimal R26_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R26_TOTAL_GENERAL_PROVISIONS;

	private String R27_PRODUCT;
	private BigDecimal R27_STAGE1_PROVISIONS;
	private BigDecimal R27_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R27_TOTAL_GENERAL_PROVISIONS;

	private String R28_PRODUCT;
	private BigDecimal R28_STAGE1_PROVISIONS;
	private BigDecimal R28_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R28_TOTAL_GENERAL_PROVISIONS;

	private String R29_PRODUCT;
	private BigDecimal R29_STAGE1_PROVISIONS;
	private BigDecimal R29_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R29_TOTAL_GENERAL_PROVISIONS;

	private String R30_PRODUCT;
	private BigDecimal R30_STAGE1_PROVISIONS;
	private BigDecimal R30_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R30_TOTAL_GENERAL_PROVISIONS;

	private String R31_PRODUCT;
	private BigDecimal R31_STAGE1_PROVISIONS;
	private BigDecimal R31_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R31_TOTAL_GENERAL_PROVISIONS;

	private String R32_PRODUCT;
	private BigDecimal R32_STAGE1_PROVISIONS;
	private BigDecimal R32_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R32_TOTAL_GENERAL_PROVISIONS;

	private String R33_PRODUCT;
	private BigDecimal R33_STAGE1_PROVISIONS;
	private BigDecimal R33_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R33_TOTAL_GENERAL_PROVISIONS;

	private String R34_PRODUCT;
	private BigDecimal R34_STAGE1_PROVISIONS;
	private BigDecimal R34_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R34_TOTAL_GENERAL_PROVISIONS;

	private String R35_PRODUCT;
	private BigDecimal R35_STAGE1_PROVISIONS;
	private BigDecimal R35_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R35_TOTAL_GENERAL_PROVISIONS;

	private String R36_PRODUCT;
	private BigDecimal R36_STAGE1_PROVISIONS;
	private BigDecimal R36_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R36_TOTAL_GENERAL_PROVISIONS;

	private String R37_PRODUCT;
	private BigDecimal R37_STAGE1_PROVISIONS;
	private BigDecimal R37_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R37_TOTAL_GENERAL_PROVISIONS;

	private String R38_PRODUCT;
	private BigDecimal R38_STAGE1_PROVISIONS;
	private BigDecimal R38_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R38_TOTAL_GENERAL_PROVISIONS;

	private String R39_PRODUCT;
	private BigDecimal R39_STAGE1_PROVISIONS;
	private BigDecimal R39_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R39_TOTAL_GENERAL_PROVISIONS;

	private String R40_PRODUCT;
	private BigDecimal R40_STAGE1_PROVISIONS;
	private BigDecimal R40_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R40_TOTAL_GENERAL_PROVISIONS;

	private String R41_PRODUCT;
	private BigDecimal R41_STAGE1_PROVISIONS;
	private BigDecimal R41_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R41_TOTAL_GENERAL_PROVISIONS;

	private String R42_PRODUCT;
	private BigDecimal R42_STAGE1_PROVISIONS;
	private BigDecimal R42_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R42_TOTAL_GENERAL_PROVISIONS;

	private String R43_PRODUCT;
	private BigDecimal R43_STAGE1_PROVISIONS;
	private BigDecimal R43_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R43_TOTAL_GENERAL_PROVISIONS;

	private String R44_PRODUCT;
	private BigDecimal R44_STAGE1_PROVISIONS;
	private BigDecimal R44_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R44_TOTAL_GENERAL_PROVISIONS;

	private String R45_PRODUCT;
	private BigDecimal R45_STAGE1_PROVISIONS;
	private BigDecimal R45_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R45_TOTAL_GENERAL_PROVISIONS;

	private String R46_PRODUCT;
	private BigDecimal R46_STAGE1_PROVISIONS;
	private BigDecimal R46_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R46_TOTAL_GENERAL_PROVISIONS;

	private String R47_PRODUCT;
	private BigDecimal R47_STAGE1_PROVISIONS;
	private BigDecimal R47_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R47_TOTAL_GENERAL_PROVISIONS;

	private String R48_PRODUCT;
	private BigDecimal R48_STAGE1_PROVISIONS;
	private BigDecimal R48_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R48_TOTAL_GENERAL_PROVISIONS;

	private String R49_PRODUCT;
	private BigDecimal R49_STAGE1_PROVISIONS;
	private BigDecimal R49_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R49_TOTAL_GENERAL_PROVISIONS;

	private String R50_PRODUCT;
	private BigDecimal R50_STAGE1_PROVISIONS;
	private BigDecimal R50_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R50_TOTAL_GENERAL_PROVISIONS;

	private String R51_PRODUCT;
	private BigDecimal R51_STAGE1_PROVISIONS;
	private BigDecimal R51_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R51_TOTAL_GENERAL_PROVISIONS;

	private String R52_PRODUCT;
	private BigDecimal R52_STAGE1_PROVISIONS;
	private BigDecimal R52_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R52_TOTAL_GENERAL_PROVISIONS;

	private String R53_PRODUCT;
	private BigDecimal R53_STAGE1_PROVISIONS;
	private BigDecimal R53_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R53_TOTAL_GENERAL_PROVISIONS;

	private String R54_PRODUCT;
	private BigDecimal R54_STAGE1_PROVISIONS;
	private BigDecimal R54_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R54_TOTAL_GENERAL_PROVISIONS;

	private String R55_PRODUCT;
	private BigDecimal R55_STAGE1_PROVISIONS;
	private BigDecimal R55_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R55_TOTAL_GENERAL_PROVISIONS;

	private String R56_PRODUCT;
	private BigDecimal R56_STAGE1_PROVISIONS;
	private BigDecimal R56_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R56_TOTAL_GENERAL_PROVISIONS;

	private String R57_PRODUCT;
	private BigDecimal R57_STAGE1_PROVISIONS;
	private BigDecimal R57_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R57_TOTAL_GENERAL_PROVISIONS;

	private String R58_PRODUCT;
	private BigDecimal R58_STAGE1_PROVISIONS;
	private BigDecimal R58_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R58_TOTAL_GENERAL_PROVISIONS;

	private String R59_PRODUCT;
	private BigDecimal R59_STAGE1_PROVISIONS;
	private BigDecimal R59_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R59_TOTAL_GENERAL_PROVISIONS;

	private String R60_PRODUCT;
	private BigDecimal R60_STAGE1_PROVISIONS;
	private BigDecimal R60_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R60_TOTAL_GENERAL_PROVISIONS;

	private String R61_PRODUCT;
	private BigDecimal R61_STAGE1_PROVISIONS;
	private BigDecimal R61_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R61_TOTAL_GENERAL_PROVISIONS;

	private String R62_PRODUCT;
	private BigDecimal R62_STAGE1_PROVISIONS;
	private BigDecimal R62_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R62_TOTAL_GENERAL_PROVISIONS;

	private String R63_PRODUCT;
	private BigDecimal R63_STAGE1_PROVISIONS;
	private BigDecimal R63_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R63_TOTAL_GENERAL_PROVISIONS;

	private String R64_PRODUCT;
	private BigDecimal R64_STAGE1_PROVISIONS;
	private BigDecimal R64_QUALIFY_STAGE2_PROVISIONS;
	private BigDecimal R64_TOTAL_GENERAL_PROVISIONS;


    @Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	public Date REPORT_DATE;
    public String REPORT_VERSION;
    public String REPORT_FREQUENCY;
    public String REPORT_CODE;
    public String REPORT_DESC;
    public String ENTITY_FLG;
    public String MODIFY_FLG;
    public String DEL_FLG;
	public String getR11_PRODUCT() {
		return R11_PRODUCT;
	}
	public void setR11_PRODUCT(String r11_PRODUCT) {
		R11_PRODUCT = r11_PRODUCT;
	}
	public BigDecimal getR11_STAGE1_PROVISIONS() {
		return R11_STAGE1_PROVISIONS;
	}
	public void setR11_STAGE1_PROVISIONS(BigDecimal r11_STAGE1_PROVISIONS) {
		R11_STAGE1_PROVISIONS = r11_STAGE1_PROVISIONS;
	}
	public BigDecimal getR11_QUALIFY_STAGE2_PROVISIONS() {
		return R11_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR11_QUALIFY_STAGE2_PROVISIONS(BigDecimal r11_QUALIFY_STAGE2_PROVISIONS) {
		R11_QUALIFY_STAGE2_PROVISIONS = r11_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR11_TOTAL_GENERAL_PROVISIONS() {
		return R11_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR11_TOTAL_GENERAL_PROVISIONS(BigDecimal r11_TOTAL_GENERAL_PROVISIONS) {
		R11_TOTAL_GENERAL_PROVISIONS = r11_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR12_PRODUCT() {
		return R12_PRODUCT;
	}
	public void setR12_PRODUCT(String r12_PRODUCT) {
		R12_PRODUCT = r12_PRODUCT;
	}
	public BigDecimal getR12_STAGE1_PROVISIONS() {
		return R12_STAGE1_PROVISIONS;
	}
	public void setR12_STAGE1_PROVISIONS(BigDecimal r12_STAGE1_PROVISIONS) {
		R12_STAGE1_PROVISIONS = r12_STAGE1_PROVISIONS;
	}
	public BigDecimal getR12_QUALIFY_STAGE2_PROVISIONS() {
		return R12_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR12_QUALIFY_STAGE2_PROVISIONS(BigDecimal r12_QUALIFY_STAGE2_PROVISIONS) {
		R12_QUALIFY_STAGE2_PROVISIONS = r12_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR12_TOTAL_GENERAL_PROVISIONS() {
		return R12_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR12_TOTAL_GENERAL_PROVISIONS(BigDecimal r12_TOTAL_GENERAL_PROVISIONS) {
		R12_TOTAL_GENERAL_PROVISIONS = r12_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR13_PRODUCT() {
		return R13_PRODUCT;
	}
	public void setR13_PRODUCT(String r13_PRODUCT) {
		R13_PRODUCT = r13_PRODUCT;
	}
	public BigDecimal getR13_STAGE1_PROVISIONS() {
		return R13_STAGE1_PROVISIONS;
	}
	public void setR13_STAGE1_PROVISIONS(BigDecimal r13_STAGE1_PROVISIONS) {
		R13_STAGE1_PROVISIONS = r13_STAGE1_PROVISIONS;
	}
	public BigDecimal getR13_QUALIFY_STAGE2_PROVISIONS() {
		return R13_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR13_QUALIFY_STAGE2_PROVISIONS(BigDecimal r13_QUALIFY_STAGE2_PROVISIONS) {
		R13_QUALIFY_STAGE2_PROVISIONS = r13_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR13_TOTAL_GENERAL_PROVISIONS() {
		return R13_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR13_TOTAL_GENERAL_PROVISIONS(BigDecimal r13_TOTAL_GENERAL_PROVISIONS) {
		R13_TOTAL_GENERAL_PROVISIONS = r13_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR14_PRODUCT() {
		return R14_PRODUCT;
	}
	public void setR14_PRODUCT(String r14_PRODUCT) {
		R14_PRODUCT = r14_PRODUCT;
	}
	public BigDecimal getR14_STAGE1_PROVISIONS() {
		return R14_STAGE1_PROVISIONS;
	}
	public void setR14_STAGE1_PROVISIONS(BigDecimal r14_STAGE1_PROVISIONS) {
		R14_STAGE1_PROVISIONS = r14_STAGE1_PROVISIONS;
	}
	public BigDecimal getR14_QUALIFY_STAGE2_PROVISIONS() {
		return R14_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR14_QUALIFY_STAGE2_PROVISIONS(BigDecimal r14_QUALIFY_STAGE2_PROVISIONS) {
		R14_QUALIFY_STAGE2_PROVISIONS = r14_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR14_TOTAL_GENERAL_PROVISIONS() {
		return R14_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR14_TOTAL_GENERAL_PROVISIONS(BigDecimal r14_TOTAL_GENERAL_PROVISIONS) {
		R14_TOTAL_GENERAL_PROVISIONS = r14_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR15_PRODUCT() {
		return R15_PRODUCT;
	}
	public void setR15_PRODUCT(String r15_PRODUCT) {
		R15_PRODUCT = r15_PRODUCT;
	}
	public BigDecimal getR15_STAGE1_PROVISIONS() {
		return R15_STAGE1_PROVISIONS;
	}
	public void setR15_STAGE1_PROVISIONS(BigDecimal r15_STAGE1_PROVISIONS) {
		R15_STAGE1_PROVISIONS = r15_STAGE1_PROVISIONS;
	}
	public BigDecimal getR15_QUALIFY_STAGE2_PROVISIONS() {
		return R15_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR15_QUALIFY_STAGE2_PROVISIONS(BigDecimal r15_QUALIFY_STAGE2_PROVISIONS) {
		R15_QUALIFY_STAGE2_PROVISIONS = r15_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR15_TOTAL_GENERAL_PROVISIONS() {
		return R15_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR15_TOTAL_GENERAL_PROVISIONS(BigDecimal r15_TOTAL_GENERAL_PROVISIONS) {
		R15_TOTAL_GENERAL_PROVISIONS = r15_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR16_PRODUCT() {
		return R16_PRODUCT;
	}
	public void setR16_PRODUCT(String r16_PRODUCT) {
		R16_PRODUCT = r16_PRODUCT;
	}
	public BigDecimal getR16_STAGE1_PROVISIONS() {
		return R16_STAGE1_PROVISIONS;
	}
	public void setR16_STAGE1_PROVISIONS(BigDecimal r16_STAGE1_PROVISIONS) {
		R16_STAGE1_PROVISIONS = r16_STAGE1_PROVISIONS;
	}
	public BigDecimal getR16_QUALIFY_STAGE2_PROVISIONS() {
		return R16_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR16_QUALIFY_STAGE2_PROVISIONS(BigDecimal r16_QUALIFY_STAGE2_PROVISIONS) {
		R16_QUALIFY_STAGE2_PROVISIONS = r16_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR16_TOTAL_GENERAL_PROVISIONS() {
		return R16_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR16_TOTAL_GENERAL_PROVISIONS(BigDecimal r16_TOTAL_GENERAL_PROVISIONS) {
		R16_TOTAL_GENERAL_PROVISIONS = r16_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR17_PRODUCT() {
		return R17_PRODUCT;
	}
	public void setR17_PRODUCT(String r17_PRODUCT) {
		R17_PRODUCT = r17_PRODUCT;
	}
	public BigDecimal getR17_STAGE1_PROVISIONS() {
		return R17_STAGE1_PROVISIONS;
	}
	public void setR17_STAGE1_PROVISIONS(BigDecimal r17_STAGE1_PROVISIONS) {
		R17_STAGE1_PROVISIONS = r17_STAGE1_PROVISIONS;
	}
	public BigDecimal getR17_QUALIFY_STAGE2_PROVISIONS() {
		return R17_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR17_QUALIFY_STAGE2_PROVISIONS(BigDecimal r17_QUALIFY_STAGE2_PROVISIONS) {
		R17_QUALIFY_STAGE2_PROVISIONS = r17_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR17_TOTAL_GENERAL_PROVISIONS() {
		return R17_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR17_TOTAL_GENERAL_PROVISIONS(BigDecimal r17_TOTAL_GENERAL_PROVISIONS) {
		R17_TOTAL_GENERAL_PROVISIONS = r17_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR18_PRODUCT() {
		return R18_PRODUCT;
	}
	public void setR18_PRODUCT(String r18_PRODUCT) {
		R18_PRODUCT = r18_PRODUCT;
	}
	public BigDecimal getR18_STAGE1_PROVISIONS() {
		return R18_STAGE1_PROVISIONS;
	}
	public void setR18_STAGE1_PROVISIONS(BigDecimal r18_STAGE1_PROVISIONS) {
		R18_STAGE1_PROVISIONS = r18_STAGE1_PROVISIONS;
	}
	public BigDecimal getR18_QUALIFY_STAGE2_PROVISIONS() {
		return R18_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR18_QUALIFY_STAGE2_PROVISIONS(BigDecimal r18_QUALIFY_STAGE2_PROVISIONS) {
		R18_QUALIFY_STAGE2_PROVISIONS = r18_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR18_TOTAL_GENERAL_PROVISIONS() {
		return R18_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR18_TOTAL_GENERAL_PROVISIONS(BigDecimal r18_TOTAL_GENERAL_PROVISIONS) {
		R18_TOTAL_GENERAL_PROVISIONS = r18_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR19_PRODUCT() {
		return R19_PRODUCT;
	}
	public void setR19_PRODUCT(String r19_PRODUCT) {
		R19_PRODUCT = r19_PRODUCT;
	}
	public BigDecimal getR19_STAGE1_PROVISIONS() {
		return R19_STAGE1_PROVISIONS;
	}
	public void setR19_STAGE1_PROVISIONS(BigDecimal r19_STAGE1_PROVISIONS) {
		R19_STAGE1_PROVISIONS = r19_STAGE1_PROVISIONS;
	}
	public BigDecimal getR19_QUALIFY_STAGE2_PROVISIONS() {
		return R19_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR19_QUALIFY_STAGE2_PROVISIONS(BigDecimal r19_QUALIFY_STAGE2_PROVISIONS) {
		R19_QUALIFY_STAGE2_PROVISIONS = r19_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR19_TOTAL_GENERAL_PROVISIONS() {
		return R19_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR19_TOTAL_GENERAL_PROVISIONS(BigDecimal r19_TOTAL_GENERAL_PROVISIONS) {
		R19_TOTAL_GENERAL_PROVISIONS = r19_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR20_PRODUCT() {
		return R20_PRODUCT;
	}
	public void setR20_PRODUCT(String r20_PRODUCT) {
		R20_PRODUCT = r20_PRODUCT;
	}
	public BigDecimal getR20_STAGE1_PROVISIONS() {
		return R20_STAGE1_PROVISIONS;
	}
	public void setR20_STAGE1_PROVISIONS(BigDecimal r20_STAGE1_PROVISIONS) {
		R20_STAGE1_PROVISIONS = r20_STAGE1_PROVISIONS;
	}
	public BigDecimal getR20_QUALIFY_STAGE2_PROVISIONS() {
		return R20_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR20_QUALIFY_STAGE2_PROVISIONS(BigDecimal r20_QUALIFY_STAGE2_PROVISIONS) {
		R20_QUALIFY_STAGE2_PROVISIONS = r20_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR20_TOTAL_GENERAL_PROVISIONS() {
		return R20_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR20_TOTAL_GENERAL_PROVISIONS(BigDecimal r20_TOTAL_GENERAL_PROVISIONS) {
		R20_TOTAL_GENERAL_PROVISIONS = r20_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR21_PRODUCT() {
		return R21_PRODUCT;
	}
	public void setR21_PRODUCT(String r21_PRODUCT) {
		R21_PRODUCT = r21_PRODUCT;
	}
	public BigDecimal getR21_STAGE1_PROVISIONS() {
		return R21_STAGE1_PROVISIONS;
	}
	public void setR21_STAGE1_PROVISIONS(BigDecimal r21_STAGE1_PROVISIONS) {
		R21_STAGE1_PROVISIONS = r21_STAGE1_PROVISIONS;
	}
	public BigDecimal getR21_QUALIFY_STAGE2_PROVISIONS() {
		return R21_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR21_QUALIFY_STAGE2_PROVISIONS(BigDecimal r21_QUALIFY_STAGE2_PROVISIONS) {
		R21_QUALIFY_STAGE2_PROVISIONS = r21_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR21_TOTAL_GENERAL_PROVISIONS() {
		return R21_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR21_TOTAL_GENERAL_PROVISIONS(BigDecimal r21_TOTAL_GENERAL_PROVISIONS) {
		R21_TOTAL_GENERAL_PROVISIONS = r21_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR22_PRODUCT() {
		return R22_PRODUCT;
	}
	public void setR22_PRODUCT(String r22_PRODUCT) {
		R22_PRODUCT = r22_PRODUCT;
	}
	public BigDecimal getR22_STAGE1_PROVISIONS() {
		return R22_STAGE1_PROVISIONS;
	}
	public void setR22_STAGE1_PROVISIONS(BigDecimal r22_STAGE1_PROVISIONS) {
		R22_STAGE1_PROVISIONS = r22_STAGE1_PROVISIONS;
	}
	public BigDecimal getR22_QUALIFY_STAGE2_PROVISIONS() {
		return R22_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR22_QUALIFY_STAGE2_PROVISIONS(BigDecimal r22_QUALIFY_STAGE2_PROVISIONS) {
		R22_QUALIFY_STAGE2_PROVISIONS = r22_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR22_TOTAL_GENERAL_PROVISIONS() {
		return R22_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR22_TOTAL_GENERAL_PROVISIONS(BigDecimal r22_TOTAL_GENERAL_PROVISIONS) {
		R22_TOTAL_GENERAL_PROVISIONS = r22_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR23_PRODUCT() {
		return R23_PRODUCT;
	}
	public void setR23_PRODUCT(String r23_PRODUCT) {
		R23_PRODUCT = r23_PRODUCT;
	}
	public BigDecimal getR23_STAGE1_PROVISIONS() {
		return R23_STAGE1_PROVISIONS;
	}
	public void setR23_STAGE1_PROVISIONS(BigDecimal r23_STAGE1_PROVISIONS) {
		R23_STAGE1_PROVISIONS = r23_STAGE1_PROVISIONS;
	}
	public BigDecimal getR23_QUALIFY_STAGE2_PROVISIONS() {
		return R23_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR23_QUALIFY_STAGE2_PROVISIONS(BigDecimal r23_QUALIFY_STAGE2_PROVISIONS) {
		R23_QUALIFY_STAGE2_PROVISIONS = r23_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR23_TOTAL_GENERAL_PROVISIONS() {
		return R23_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR23_TOTAL_GENERAL_PROVISIONS(BigDecimal r23_TOTAL_GENERAL_PROVISIONS) {
		R23_TOTAL_GENERAL_PROVISIONS = r23_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR24_PRODUCT() {
		return R24_PRODUCT;
	}
	public void setR24_PRODUCT(String r24_PRODUCT) {
		R24_PRODUCT = r24_PRODUCT;
	}
	public BigDecimal getR24_STAGE1_PROVISIONS() {
		return R24_STAGE1_PROVISIONS;
	}
	public void setR24_STAGE1_PROVISIONS(BigDecimal r24_STAGE1_PROVISIONS) {
		R24_STAGE1_PROVISIONS = r24_STAGE1_PROVISIONS;
	}
	public BigDecimal getR24_QUALIFY_STAGE2_PROVISIONS() {
		return R24_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR24_QUALIFY_STAGE2_PROVISIONS(BigDecimal r24_QUALIFY_STAGE2_PROVISIONS) {
		R24_QUALIFY_STAGE2_PROVISIONS = r24_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR24_TOTAL_GENERAL_PROVISIONS() {
		return R24_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR24_TOTAL_GENERAL_PROVISIONS(BigDecimal r24_TOTAL_GENERAL_PROVISIONS) {
		R24_TOTAL_GENERAL_PROVISIONS = r24_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR25_PRODUCT() {
		return R25_PRODUCT;
	}
	public void setR25_PRODUCT(String r25_PRODUCT) {
		R25_PRODUCT = r25_PRODUCT;
	}
	public BigDecimal getR25_STAGE1_PROVISIONS() {
		return R25_STAGE1_PROVISIONS;
	}
	public void setR25_STAGE1_PROVISIONS(BigDecimal r25_STAGE1_PROVISIONS) {
		R25_STAGE1_PROVISIONS = r25_STAGE1_PROVISIONS;
	}
	public BigDecimal getR25_QUALIFY_STAGE2_PROVISIONS() {
		return R25_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR25_QUALIFY_STAGE2_PROVISIONS(BigDecimal r25_QUALIFY_STAGE2_PROVISIONS) {
		R25_QUALIFY_STAGE2_PROVISIONS = r25_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR25_TOTAL_GENERAL_PROVISIONS() {
		return R25_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR25_TOTAL_GENERAL_PROVISIONS(BigDecimal r25_TOTAL_GENERAL_PROVISIONS) {
		R25_TOTAL_GENERAL_PROVISIONS = r25_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR26_PRODUCT() {
		return R26_PRODUCT;
	}
	public void setR26_PRODUCT(String r26_PRODUCT) {
		R26_PRODUCT = r26_PRODUCT;
	}
	public BigDecimal getR26_STAGE1_PROVISIONS() {
		return R26_STAGE1_PROVISIONS;
	}
	public void setR26_STAGE1_PROVISIONS(BigDecimal r26_STAGE1_PROVISIONS) {
		R26_STAGE1_PROVISIONS = r26_STAGE1_PROVISIONS;
	}
	public BigDecimal getR26_QUALIFY_STAGE2_PROVISIONS() {
		return R26_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR26_QUALIFY_STAGE2_PROVISIONS(BigDecimal r26_QUALIFY_STAGE2_PROVISIONS) {
		R26_QUALIFY_STAGE2_PROVISIONS = r26_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR26_TOTAL_GENERAL_PROVISIONS() {
		return R26_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR26_TOTAL_GENERAL_PROVISIONS(BigDecimal r26_TOTAL_GENERAL_PROVISIONS) {
		R26_TOTAL_GENERAL_PROVISIONS = r26_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR27_PRODUCT() {
		return R27_PRODUCT;
	}
	public void setR27_PRODUCT(String r27_PRODUCT) {
		R27_PRODUCT = r27_PRODUCT;
	}
	public BigDecimal getR27_STAGE1_PROVISIONS() {
		return R27_STAGE1_PROVISIONS;
	}
	public void setR27_STAGE1_PROVISIONS(BigDecimal r27_STAGE1_PROVISIONS) {
		R27_STAGE1_PROVISIONS = r27_STAGE1_PROVISIONS;
	}
	public BigDecimal getR27_QUALIFY_STAGE2_PROVISIONS() {
		return R27_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR27_QUALIFY_STAGE2_PROVISIONS(BigDecimal r27_QUALIFY_STAGE2_PROVISIONS) {
		R27_QUALIFY_STAGE2_PROVISIONS = r27_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR27_TOTAL_GENERAL_PROVISIONS() {
		return R27_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR27_TOTAL_GENERAL_PROVISIONS(BigDecimal r27_TOTAL_GENERAL_PROVISIONS) {
		R27_TOTAL_GENERAL_PROVISIONS = r27_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR28_PRODUCT() {
		return R28_PRODUCT;
	}
	public void setR28_PRODUCT(String r28_PRODUCT) {
		R28_PRODUCT = r28_PRODUCT;
	}
	public BigDecimal getR28_STAGE1_PROVISIONS() {
		return R28_STAGE1_PROVISIONS;
	}
	public void setR28_STAGE1_PROVISIONS(BigDecimal r28_STAGE1_PROVISIONS) {
		R28_STAGE1_PROVISIONS = r28_STAGE1_PROVISIONS;
	}
	public BigDecimal getR28_QUALIFY_STAGE2_PROVISIONS() {
		return R28_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR28_QUALIFY_STAGE2_PROVISIONS(BigDecimal r28_QUALIFY_STAGE2_PROVISIONS) {
		R28_QUALIFY_STAGE2_PROVISIONS = r28_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR28_TOTAL_GENERAL_PROVISIONS() {
		return R28_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR28_TOTAL_GENERAL_PROVISIONS(BigDecimal r28_TOTAL_GENERAL_PROVISIONS) {
		R28_TOTAL_GENERAL_PROVISIONS = r28_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR29_PRODUCT() {
		return R29_PRODUCT;
	}
	public void setR29_PRODUCT(String r29_PRODUCT) {
		R29_PRODUCT = r29_PRODUCT;
	}
	public BigDecimal getR29_STAGE1_PROVISIONS() {
		return R29_STAGE1_PROVISIONS;
	}
	public void setR29_STAGE1_PROVISIONS(BigDecimal r29_STAGE1_PROVISIONS) {
		R29_STAGE1_PROVISIONS = r29_STAGE1_PROVISIONS;
	}
	public BigDecimal getR29_QUALIFY_STAGE2_PROVISIONS() {
		return R29_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR29_QUALIFY_STAGE2_PROVISIONS(BigDecimal r29_QUALIFY_STAGE2_PROVISIONS) {
		R29_QUALIFY_STAGE2_PROVISIONS = r29_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR29_TOTAL_GENERAL_PROVISIONS() {
		return R29_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR29_TOTAL_GENERAL_PROVISIONS(BigDecimal r29_TOTAL_GENERAL_PROVISIONS) {
		R29_TOTAL_GENERAL_PROVISIONS = r29_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR30_PRODUCT() {
		return R30_PRODUCT;
	}
	public void setR30_PRODUCT(String r30_PRODUCT) {
		R30_PRODUCT = r30_PRODUCT;
	}
	public BigDecimal getR30_STAGE1_PROVISIONS() {
		return R30_STAGE1_PROVISIONS;
	}
	public void setR30_STAGE1_PROVISIONS(BigDecimal r30_STAGE1_PROVISIONS) {
		R30_STAGE1_PROVISIONS = r30_STAGE1_PROVISIONS;
	}
	public BigDecimal getR30_QUALIFY_STAGE2_PROVISIONS() {
		return R30_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR30_QUALIFY_STAGE2_PROVISIONS(BigDecimal r30_QUALIFY_STAGE2_PROVISIONS) {
		R30_QUALIFY_STAGE2_PROVISIONS = r30_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR30_TOTAL_GENERAL_PROVISIONS() {
		return R30_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR30_TOTAL_GENERAL_PROVISIONS(BigDecimal r30_TOTAL_GENERAL_PROVISIONS) {
		R30_TOTAL_GENERAL_PROVISIONS = r30_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR31_PRODUCT() {
		return R31_PRODUCT;
	}
	public void setR31_PRODUCT(String r31_PRODUCT) {
		R31_PRODUCT = r31_PRODUCT;
	}
	public BigDecimal getR31_STAGE1_PROVISIONS() {
		return R31_STAGE1_PROVISIONS;
	}
	public void setR31_STAGE1_PROVISIONS(BigDecimal r31_STAGE1_PROVISIONS) {
		R31_STAGE1_PROVISIONS = r31_STAGE1_PROVISIONS;
	}
	public BigDecimal getR31_QUALIFY_STAGE2_PROVISIONS() {
		return R31_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR31_QUALIFY_STAGE2_PROVISIONS(BigDecimal r31_QUALIFY_STAGE2_PROVISIONS) {
		R31_QUALIFY_STAGE2_PROVISIONS = r31_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR31_TOTAL_GENERAL_PROVISIONS() {
		return R31_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR31_TOTAL_GENERAL_PROVISIONS(BigDecimal r31_TOTAL_GENERAL_PROVISIONS) {
		R31_TOTAL_GENERAL_PROVISIONS = r31_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR32_PRODUCT() {
		return R32_PRODUCT;
	}
	public void setR32_PRODUCT(String r32_PRODUCT) {
		R32_PRODUCT = r32_PRODUCT;
	}
	public BigDecimal getR32_STAGE1_PROVISIONS() {
		return R32_STAGE1_PROVISIONS;
	}
	public void setR32_STAGE1_PROVISIONS(BigDecimal r32_STAGE1_PROVISIONS) {
		R32_STAGE1_PROVISIONS = r32_STAGE1_PROVISIONS;
	}
	public BigDecimal getR32_QUALIFY_STAGE2_PROVISIONS() {
		return R32_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR32_QUALIFY_STAGE2_PROVISIONS(BigDecimal r32_QUALIFY_STAGE2_PROVISIONS) {
		R32_QUALIFY_STAGE2_PROVISIONS = r32_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR32_TOTAL_GENERAL_PROVISIONS() {
		return R32_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR32_TOTAL_GENERAL_PROVISIONS(BigDecimal r32_TOTAL_GENERAL_PROVISIONS) {
		R32_TOTAL_GENERAL_PROVISIONS = r32_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR33_PRODUCT() {
		return R33_PRODUCT;
	}
	public void setR33_PRODUCT(String r33_PRODUCT) {
		R33_PRODUCT = r33_PRODUCT;
	}
	public BigDecimal getR33_STAGE1_PROVISIONS() {
		return R33_STAGE1_PROVISIONS;
	}
	public void setR33_STAGE1_PROVISIONS(BigDecimal r33_STAGE1_PROVISIONS) {
		R33_STAGE1_PROVISIONS = r33_STAGE1_PROVISIONS;
	}
	public BigDecimal getR33_QUALIFY_STAGE2_PROVISIONS() {
		return R33_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR33_QUALIFY_STAGE2_PROVISIONS(BigDecimal r33_QUALIFY_STAGE2_PROVISIONS) {
		R33_QUALIFY_STAGE2_PROVISIONS = r33_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR33_TOTAL_GENERAL_PROVISIONS() {
		return R33_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR33_TOTAL_GENERAL_PROVISIONS(BigDecimal r33_TOTAL_GENERAL_PROVISIONS) {
		R33_TOTAL_GENERAL_PROVISIONS = r33_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR34_PRODUCT() {
		return R34_PRODUCT;
	}
	public void setR34_PRODUCT(String r34_PRODUCT) {
		R34_PRODUCT = r34_PRODUCT;
	}
	public BigDecimal getR34_STAGE1_PROVISIONS() {
		return R34_STAGE1_PROVISIONS;
	}
	public void setR34_STAGE1_PROVISIONS(BigDecimal r34_STAGE1_PROVISIONS) {
		R34_STAGE1_PROVISIONS = r34_STAGE1_PROVISIONS;
	}
	public BigDecimal getR34_QUALIFY_STAGE2_PROVISIONS() {
		return R34_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR34_QUALIFY_STAGE2_PROVISIONS(BigDecimal r34_QUALIFY_STAGE2_PROVISIONS) {
		R34_QUALIFY_STAGE2_PROVISIONS = r34_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR34_TOTAL_GENERAL_PROVISIONS() {
		return R34_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR34_TOTAL_GENERAL_PROVISIONS(BigDecimal r34_TOTAL_GENERAL_PROVISIONS) {
		R34_TOTAL_GENERAL_PROVISIONS = r34_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR35_PRODUCT() {
		return R35_PRODUCT;
	}
	public void setR35_PRODUCT(String r35_PRODUCT) {
		R35_PRODUCT = r35_PRODUCT;
	}
	public BigDecimal getR35_STAGE1_PROVISIONS() {
		return R35_STAGE1_PROVISIONS;
	}
	public void setR35_STAGE1_PROVISIONS(BigDecimal r35_STAGE1_PROVISIONS) {
		R35_STAGE1_PROVISIONS = r35_STAGE1_PROVISIONS;
	}
	public BigDecimal getR35_QUALIFY_STAGE2_PROVISIONS() {
		return R35_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR35_QUALIFY_STAGE2_PROVISIONS(BigDecimal r35_QUALIFY_STAGE2_PROVISIONS) {
		R35_QUALIFY_STAGE2_PROVISIONS = r35_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR35_TOTAL_GENERAL_PROVISIONS() {
		return R35_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR35_TOTAL_GENERAL_PROVISIONS(BigDecimal r35_TOTAL_GENERAL_PROVISIONS) {
		R35_TOTAL_GENERAL_PROVISIONS = r35_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR36_PRODUCT() {
		return R36_PRODUCT;
	}
	public void setR36_PRODUCT(String r36_PRODUCT) {
		R36_PRODUCT = r36_PRODUCT;
	}
	public BigDecimal getR36_STAGE1_PROVISIONS() {
		return R36_STAGE1_PROVISIONS;
	}
	public void setR36_STAGE1_PROVISIONS(BigDecimal r36_STAGE1_PROVISIONS) {
		R36_STAGE1_PROVISIONS = r36_STAGE1_PROVISIONS;
	}
	public BigDecimal getR36_QUALIFY_STAGE2_PROVISIONS() {
		return R36_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR36_QUALIFY_STAGE2_PROVISIONS(BigDecimal r36_QUALIFY_STAGE2_PROVISIONS) {
		R36_QUALIFY_STAGE2_PROVISIONS = r36_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR36_TOTAL_GENERAL_PROVISIONS() {
		return R36_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR36_TOTAL_GENERAL_PROVISIONS(BigDecimal r36_TOTAL_GENERAL_PROVISIONS) {
		R36_TOTAL_GENERAL_PROVISIONS = r36_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR37_PRODUCT() {
		return R37_PRODUCT;
	}
	public void setR37_PRODUCT(String r37_PRODUCT) {
		R37_PRODUCT = r37_PRODUCT;
	}
	public BigDecimal getR37_STAGE1_PROVISIONS() {
		return R37_STAGE1_PROVISIONS;
	}
	public void setR37_STAGE1_PROVISIONS(BigDecimal r37_STAGE1_PROVISIONS) {
		R37_STAGE1_PROVISIONS = r37_STAGE1_PROVISIONS;
	}
	public BigDecimal getR37_QUALIFY_STAGE2_PROVISIONS() {
		return R37_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR37_QUALIFY_STAGE2_PROVISIONS(BigDecimal r37_QUALIFY_STAGE2_PROVISIONS) {
		R37_QUALIFY_STAGE2_PROVISIONS = r37_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR37_TOTAL_GENERAL_PROVISIONS() {
		return R37_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR37_TOTAL_GENERAL_PROVISIONS(BigDecimal r37_TOTAL_GENERAL_PROVISIONS) {
		R37_TOTAL_GENERAL_PROVISIONS = r37_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR38_PRODUCT() {
		return R38_PRODUCT;
	}
	public void setR38_PRODUCT(String r38_PRODUCT) {
		R38_PRODUCT = r38_PRODUCT;
	}
	public BigDecimal getR38_STAGE1_PROVISIONS() {
		return R38_STAGE1_PROVISIONS;
	}
	public void setR38_STAGE1_PROVISIONS(BigDecimal r38_STAGE1_PROVISIONS) {
		R38_STAGE1_PROVISIONS = r38_STAGE1_PROVISIONS;
	}
	public BigDecimal getR38_QUALIFY_STAGE2_PROVISIONS() {
		return R38_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR38_QUALIFY_STAGE2_PROVISIONS(BigDecimal r38_QUALIFY_STAGE2_PROVISIONS) {
		R38_QUALIFY_STAGE2_PROVISIONS = r38_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR38_TOTAL_GENERAL_PROVISIONS() {
		return R38_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR38_TOTAL_GENERAL_PROVISIONS(BigDecimal r38_TOTAL_GENERAL_PROVISIONS) {
		R38_TOTAL_GENERAL_PROVISIONS = r38_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR39_PRODUCT() {
		return R39_PRODUCT;
	}
	public void setR39_PRODUCT(String r39_PRODUCT) {
		R39_PRODUCT = r39_PRODUCT;
	}
	public BigDecimal getR39_STAGE1_PROVISIONS() {
		return R39_STAGE1_PROVISIONS;
	}
	public void setR39_STAGE1_PROVISIONS(BigDecimal r39_STAGE1_PROVISIONS) {
		R39_STAGE1_PROVISIONS = r39_STAGE1_PROVISIONS;
	}
	public BigDecimal getR39_QUALIFY_STAGE2_PROVISIONS() {
		return R39_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR39_QUALIFY_STAGE2_PROVISIONS(BigDecimal r39_QUALIFY_STAGE2_PROVISIONS) {
		R39_QUALIFY_STAGE2_PROVISIONS = r39_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR39_TOTAL_GENERAL_PROVISIONS() {
		return R39_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR39_TOTAL_GENERAL_PROVISIONS(BigDecimal r39_TOTAL_GENERAL_PROVISIONS) {
		R39_TOTAL_GENERAL_PROVISIONS = r39_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR40_PRODUCT() {
		return R40_PRODUCT;
	}
	public void setR40_PRODUCT(String r40_PRODUCT) {
		R40_PRODUCT = r40_PRODUCT;
	}
	public BigDecimal getR40_STAGE1_PROVISIONS() {
		return R40_STAGE1_PROVISIONS;
	}
	public void setR40_STAGE1_PROVISIONS(BigDecimal r40_STAGE1_PROVISIONS) {
		R40_STAGE1_PROVISIONS = r40_STAGE1_PROVISIONS;
	}
	public BigDecimal getR40_QUALIFY_STAGE2_PROVISIONS() {
		return R40_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR40_QUALIFY_STAGE2_PROVISIONS(BigDecimal r40_QUALIFY_STAGE2_PROVISIONS) {
		R40_QUALIFY_STAGE2_PROVISIONS = r40_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR40_TOTAL_GENERAL_PROVISIONS() {
		return R40_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR40_TOTAL_GENERAL_PROVISIONS(BigDecimal r40_TOTAL_GENERAL_PROVISIONS) {
		R40_TOTAL_GENERAL_PROVISIONS = r40_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR41_PRODUCT() {
		return R41_PRODUCT;
	}
	public void setR41_PRODUCT(String r41_PRODUCT) {
		R41_PRODUCT = r41_PRODUCT;
	}
	public BigDecimal getR41_STAGE1_PROVISIONS() {
		return R41_STAGE1_PROVISIONS;
	}
	public void setR41_STAGE1_PROVISIONS(BigDecimal r41_STAGE1_PROVISIONS) {
		R41_STAGE1_PROVISIONS = r41_STAGE1_PROVISIONS;
	}
	public BigDecimal getR41_QUALIFY_STAGE2_PROVISIONS() {
		return R41_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR41_QUALIFY_STAGE2_PROVISIONS(BigDecimal r41_QUALIFY_STAGE2_PROVISIONS) {
		R41_QUALIFY_STAGE2_PROVISIONS = r41_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR41_TOTAL_GENERAL_PROVISIONS() {
		return R41_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR41_TOTAL_GENERAL_PROVISIONS(BigDecimal r41_TOTAL_GENERAL_PROVISIONS) {
		R41_TOTAL_GENERAL_PROVISIONS = r41_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR42_PRODUCT() {
		return R42_PRODUCT;
	}
	public void setR42_PRODUCT(String r42_PRODUCT) {
		R42_PRODUCT = r42_PRODUCT;
	}
	public BigDecimal getR42_STAGE1_PROVISIONS() {
		return R42_STAGE1_PROVISIONS;
	}
	public void setR42_STAGE1_PROVISIONS(BigDecimal r42_STAGE1_PROVISIONS) {
		R42_STAGE1_PROVISIONS = r42_STAGE1_PROVISIONS;
	}
	public BigDecimal getR42_QUALIFY_STAGE2_PROVISIONS() {
		return R42_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR42_QUALIFY_STAGE2_PROVISIONS(BigDecimal r42_QUALIFY_STAGE2_PROVISIONS) {
		R42_QUALIFY_STAGE2_PROVISIONS = r42_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR42_TOTAL_GENERAL_PROVISIONS() {
		return R42_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR42_TOTAL_GENERAL_PROVISIONS(BigDecimal r42_TOTAL_GENERAL_PROVISIONS) {
		R42_TOTAL_GENERAL_PROVISIONS = r42_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR43_PRODUCT() {
		return R43_PRODUCT;
	}
	public void setR43_PRODUCT(String r43_PRODUCT) {
		R43_PRODUCT = r43_PRODUCT;
	}
	public BigDecimal getR43_STAGE1_PROVISIONS() {
		return R43_STAGE1_PROVISIONS;
	}
	public void setR43_STAGE1_PROVISIONS(BigDecimal r43_STAGE1_PROVISIONS) {
		R43_STAGE1_PROVISIONS = r43_STAGE1_PROVISIONS;
	}
	public BigDecimal getR43_QUALIFY_STAGE2_PROVISIONS() {
		return R43_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR43_QUALIFY_STAGE2_PROVISIONS(BigDecimal r43_QUALIFY_STAGE2_PROVISIONS) {
		R43_QUALIFY_STAGE2_PROVISIONS = r43_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR43_TOTAL_GENERAL_PROVISIONS() {
		return R43_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR43_TOTAL_GENERAL_PROVISIONS(BigDecimal r43_TOTAL_GENERAL_PROVISIONS) {
		R43_TOTAL_GENERAL_PROVISIONS = r43_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR44_PRODUCT() {
		return R44_PRODUCT;
	}
	public void setR44_PRODUCT(String r44_PRODUCT) {
		R44_PRODUCT = r44_PRODUCT;
	}
	public BigDecimal getR44_STAGE1_PROVISIONS() {
		return R44_STAGE1_PROVISIONS;
	}
	public void setR44_STAGE1_PROVISIONS(BigDecimal r44_STAGE1_PROVISIONS) {
		R44_STAGE1_PROVISIONS = r44_STAGE1_PROVISIONS;
	}
	public BigDecimal getR44_QUALIFY_STAGE2_PROVISIONS() {
		return R44_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR44_QUALIFY_STAGE2_PROVISIONS(BigDecimal r44_QUALIFY_STAGE2_PROVISIONS) {
		R44_QUALIFY_STAGE2_PROVISIONS = r44_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR44_TOTAL_GENERAL_PROVISIONS() {
		return R44_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR44_TOTAL_GENERAL_PROVISIONS(BigDecimal r44_TOTAL_GENERAL_PROVISIONS) {
		R44_TOTAL_GENERAL_PROVISIONS = r44_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR45_PRODUCT() {
		return R45_PRODUCT;
	}
	public void setR45_PRODUCT(String r45_PRODUCT) {
		R45_PRODUCT = r45_PRODUCT;
	}
	public BigDecimal getR45_STAGE1_PROVISIONS() {
		return R45_STAGE1_PROVISIONS;
	}
	public void setR45_STAGE1_PROVISIONS(BigDecimal r45_STAGE1_PROVISIONS) {
		R45_STAGE1_PROVISIONS = r45_STAGE1_PROVISIONS;
	}
	public BigDecimal getR45_QUALIFY_STAGE2_PROVISIONS() {
		return R45_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR45_QUALIFY_STAGE2_PROVISIONS(BigDecimal r45_QUALIFY_STAGE2_PROVISIONS) {
		R45_QUALIFY_STAGE2_PROVISIONS = r45_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR45_TOTAL_GENERAL_PROVISIONS() {
		return R45_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR45_TOTAL_GENERAL_PROVISIONS(BigDecimal r45_TOTAL_GENERAL_PROVISIONS) {
		R45_TOTAL_GENERAL_PROVISIONS = r45_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR46_PRODUCT() {
		return R46_PRODUCT;
	}
	public void setR46_PRODUCT(String r46_PRODUCT) {
		R46_PRODUCT = r46_PRODUCT;
	}
	public BigDecimal getR46_STAGE1_PROVISIONS() {
		return R46_STAGE1_PROVISIONS;
	}
	public void setR46_STAGE1_PROVISIONS(BigDecimal r46_STAGE1_PROVISIONS) {
		R46_STAGE1_PROVISIONS = r46_STAGE1_PROVISIONS;
	}
	public BigDecimal getR46_QUALIFY_STAGE2_PROVISIONS() {
		return R46_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR46_QUALIFY_STAGE2_PROVISIONS(BigDecimal r46_QUALIFY_STAGE2_PROVISIONS) {
		R46_QUALIFY_STAGE2_PROVISIONS = r46_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR46_TOTAL_GENERAL_PROVISIONS() {
		return R46_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR46_TOTAL_GENERAL_PROVISIONS(BigDecimal r46_TOTAL_GENERAL_PROVISIONS) {
		R46_TOTAL_GENERAL_PROVISIONS = r46_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR47_PRODUCT() {
		return R47_PRODUCT;
	}
	public void setR47_PRODUCT(String r47_PRODUCT) {
		R47_PRODUCT = r47_PRODUCT;
	}
	public BigDecimal getR47_STAGE1_PROVISIONS() {
		return R47_STAGE1_PROVISIONS;
	}
	public void setR47_STAGE1_PROVISIONS(BigDecimal r47_STAGE1_PROVISIONS) {
		R47_STAGE1_PROVISIONS = r47_STAGE1_PROVISIONS;
	}
	public BigDecimal getR47_QUALIFY_STAGE2_PROVISIONS() {
		return R47_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR47_QUALIFY_STAGE2_PROVISIONS(BigDecimal r47_QUALIFY_STAGE2_PROVISIONS) {
		R47_QUALIFY_STAGE2_PROVISIONS = r47_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR47_TOTAL_GENERAL_PROVISIONS() {
		return R47_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR47_TOTAL_GENERAL_PROVISIONS(BigDecimal r47_TOTAL_GENERAL_PROVISIONS) {
		R47_TOTAL_GENERAL_PROVISIONS = r47_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR48_PRODUCT() {
		return R48_PRODUCT;
	}
	public void setR48_PRODUCT(String r48_PRODUCT) {
		R48_PRODUCT = r48_PRODUCT;
	}
	public BigDecimal getR48_STAGE1_PROVISIONS() {
		return R48_STAGE1_PROVISIONS;
	}
	public void setR48_STAGE1_PROVISIONS(BigDecimal r48_STAGE1_PROVISIONS) {
		R48_STAGE1_PROVISIONS = r48_STAGE1_PROVISIONS;
	}
	public BigDecimal getR48_QUALIFY_STAGE2_PROVISIONS() {
		return R48_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR48_QUALIFY_STAGE2_PROVISIONS(BigDecimal r48_QUALIFY_STAGE2_PROVISIONS) {
		R48_QUALIFY_STAGE2_PROVISIONS = r48_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR48_TOTAL_GENERAL_PROVISIONS() {
		return R48_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR48_TOTAL_GENERAL_PROVISIONS(BigDecimal r48_TOTAL_GENERAL_PROVISIONS) {
		R48_TOTAL_GENERAL_PROVISIONS = r48_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR49_PRODUCT() {
		return R49_PRODUCT;
	}
	public void setR49_PRODUCT(String r49_PRODUCT) {
		R49_PRODUCT = r49_PRODUCT;
	}
	public BigDecimal getR49_STAGE1_PROVISIONS() {
		return R49_STAGE1_PROVISIONS;
	}
	public void setR49_STAGE1_PROVISIONS(BigDecimal r49_STAGE1_PROVISIONS) {
		R49_STAGE1_PROVISIONS = r49_STAGE1_PROVISIONS;
	}
	public BigDecimal getR49_QUALIFY_STAGE2_PROVISIONS() {
		return R49_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR49_QUALIFY_STAGE2_PROVISIONS(BigDecimal r49_QUALIFY_STAGE2_PROVISIONS) {
		R49_QUALIFY_STAGE2_PROVISIONS = r49_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR49_TOTAL_GENERAL_PROVISIONS() {
		return R49_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR49_TOTAL_GENERAL_PROVISIONS(BigDecimal r49_TOTAL_GENERAL_PROVISIONS) {
		R49_TOTAL_GENERAL_PROVISIONS = r49_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR50_PRODUCT() {
		return R50_PRODUCT;
	}
	public void setR50_PRODUCT(String r50_PRODUCT) {
		R50_PRODUCT = r50_PRODUCT;
	}
	public BigDecimal getR50_STAGE1_PROVISIONS() {
		return R50_STAGE1_PROVISIONS;
	}
	public void setR50_STAGE1_PROVISIONS(BigDecimal r50_STAGE1_PROVISIONS) {
		R50_STAGE1_PROVISIONS = r50_STAGE1_PROVISIONS;
	}
	public BigDecimal getR50_QUALIFY_STAGE2_PROVISIONS() {
		return R50_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR50_QUALIFY_STAGE2_PROVISIONS(BigDecimal r50_QUALIFY_STAGE2_PROVISIONS) {
		R50_QUALIFY_STAGE2_PROVISIONS = r50_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR50_TOTAL_GENERAL_PROVISIONS() {
		return R50_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR50_TOTAL_GENERAL_PROVISIONS(BigDecimal r50_TOTAL_GENERAL_PROVISIONS) {
		R50_TOTAL_GENERAL_PROVISIONS = r50_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR51_PRODUCT() {
		return R51_PRODUCT;
	}
	public void setR51_PRODUCT(String r51_PRODUCT) {
		R51_PRODUCT = r51_PRODUCT;
	}
	public BigDecimal getR51_STAGE1_PROVISIONS() {
		return R51_STAGE1_PROVISIONS;
	}
	public void setR51_STAGE1_PROVISIONS(BigDecimal r51_STAGE1_PROVISIONS) {
		R51_STAGE1_PROVISIONS = r51_STAGE1_PROVISIONS;
	}
	public BigDecimal getR51_QUALIFY_STAGE2_PROVISIONS() {
		return R51_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR51_QUALIFY_STAGE2_PROVISIONS(BigDecimal r51_QUALIFY_STAGE2_PROVISIONS) {
		R51_QUALIFY_STAGE2_PROVISIONS = r51_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR51_TOTAL_GENERAL_PROVISIONS() {
		return R51_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR51_TOTAL_GENERAL_PROVISIONS(BigDecimal r51_TOTAL_GENERAL_PROVISIONS) {
		R51_TOTAL_GENERAL_PROVISIONS = r51_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR52_PRODUCT() {
		return R52_PRODUCT;
	}
	public void setR52_PRODUCT(String r52_PRODUCT) {
		R52_PRODUCT = r52_PRODUCT;
	}
	public BigDecimal getR52_STAGE1_PROVISIONS() {
		return R52_STAGE1_PROVISIONS;
	}
	public void setR52_STAGE1_PROVISIONS(BigDecimal r52_STAGE1_PROVISIONS) {
		R52_STAGE1_PROVISIONS = r52_STAGE1_PROVISIONS;
	}
	public BigDecimal getR52_QUALIFY_STAGE2_PROVISIONS() {
		return R52_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR52_QUALIFY_STAGE2_PROVISIONS(BigDecimal r52_QUALIFY_STAGE2_PROVISIONS) {
		R52_QUALIFY_STAGE2_PROVISIONS = r52_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR52_TOTAL_GENERAL_PROVISIONS() {
		return R52_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR52_TOTAL_GENERAL_PROVISIONS(BigDecimal r52_TOTAL_GENERAL_PROVISIONS) {
		R52_TOTAL_GENERAL_PROVISIONS = r52_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR53_PRODUCT() {
		return R53_PRODUCT;
	}
	public void setR53_PRODUCT(String r53_PRODUCT) {
		R53_PRODUCT = r53_PRODUCT;
	}
	public BigDecimal getR53_STAGE1_PROVISIONS() {
		return R53_STAGE1_PROVISIONS;
	}
	public void setR53_STAGE1_PROVISIONS(BigDecimal r53_STAGE1_PROVISIONS) {
		R53_STAGE1_PROVISIONS = r53_STAGE1_PROVISIONS;
	}
	public BigDecimal getR53_QUALIFY_STAGE2_PROVISIONS() {
		return R53_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR53_QUALIFY_STAGE2_PROVISIONS(BigDecimal r53_QUALIFY_STAGE2_PROVISIONS) {
		R53_QUALIFY_STAGE2_PROVISIONS = r53_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR53_TOTAL_GENERAL_PROVISIONS() {
		return R53_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR53_TOTAL_GENERAL_PROVISIONS(BigDecimal r53_TOTAL_GENERAL_PROVISIONS) {
		R53_TOTAL_GENERAL_PROVISIONS = r53_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR54_PRODUCT() {
		return R54_PRODUCT;
	}
	public void setR54_PRODUCT(String r54_PRODUCT) {
		R54_PRODUCT = r54_PRODUCT;
	}
	public BigDecimal getR54_STAGE1_PROVISIONS() {
		return R54_STAGE1_PROVISIONS;
	}
	public void setR54_STAGE1_PROVISIONS(BigDecimal r54_STAGE1_PROVISIONS) {
		R54_STAGE1_PROVISIONS = r54_STAGE1_PROVISIONS;
	}
	public BigDecimal getR54_QUALIFY_STAGE2_PROVISIONS() {
		return R54_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR54_QUALIFY_STAGE2_PROVISIONS(BigDecimal r54_QUALIFY_STAGE2_PROVISIONS) {
		R54_QUALIFY_STAGE2_PROVISIONS = r54_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR54_TOTAL_GENERAL_PROVISIONS() {
		return R54_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR54_TOTAL_GENERAL_PROVISIONS(BigDecimal r54_TOTAL_GENERAL_PROVISIONS) {
		R54_TOTAL_GENERAL_PROVISIONS = r54_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR55_PRODUCT() {
		return R55_PRODUCT;
	}
	public void setR55_PRODUCT(String r55_PRODUCT) {
		R55_PRODUCT = r55_PRODUCT;
	}
	public BigDecimal getR55_STAGE1_PROVISIONS() {
		return R55_STAGE1_PROVISIONS;
	}
	public void setR55_STAGE1_PROVISIONS(BigDecimal r55_STAGE1_PROVISIONS) {
		R55_STAGE1_PROVISIONS = r55_STAGE1_PROVISIONS;
	}
	public BigDecimal getR55_QUALIFY_STAGE2_PROVISIONS() {
		return R55_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR55_QUALIFY_STAGE2_PROVISIONS(BigDecimal r55_QUALIFY_STAGE2_PROVISIONS) {
		R55_QUALIFY_STAGE2_PROVISIONS = r55_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR55_TOTAL_GENERAL_PROVISIONS() {
		return R55_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR55_TOTAL_GENERAL_PROVISIONS(BigDecimal r55_TOTAL_GENERAL_PROVISIONS) {
		R55_TOTAL_GENERAL_PROVISIONS = r55_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR56_PRODUCT() {
		return R56_PRODUCT;
	}
	public void setR56_PRODUCT(String r56_PRODUCT) {
		R56_PRODUCT = r56_PRODUCT;
	}
	public BigDecimal getR56_STAGE1_PROVISIONS() {
		return R56_STAGE1_PROVISIONS;
	}
	public void setR56_STAGE1_PROVISIONS(BigDecimal r56_STAGE1_PROVISIONS) {
		R56_STAGE1_PROVISIONS = r56_STAGE1_PROVISIONS;
	}
	public BigDecimal getR56_QUALIFY_STAGE2_PROVISIONS() {
		return R56_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR56_QUALIFY_STAGE2_PROVISIONS(BigDecimal r56_QUALIFY_STAGE2_PROVISIONS) {
		R56_QUALIFY_STAGE2_PROVISIONS = r56_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR56_TOTAL_GENERAL_PROVISIONS() {
		return R56_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR56_TOTAL_GENERAL_PROVISIONS(BigDecimal r56_TOTAL_GENERAL_PROVISIONS) {
		R56_TOTAL_GENERAL_PROVISIONS = r56_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR57_PRODUCT() {
		return R57_PRODUCT;
	}
	public void setR57_PRODUCT(String r57_PRODUCT) {
		R57_PRODUCT = r57_PRODUCT;
	}
	public BigDecimal getR57_STAGE1_PROVISIONS() {
		return R57_STAGE1_PROVISIONS;
	}
	public void setR57_STAGE1_PROVISIONS(BigDecimal r57_STAGE1_PROVISIONS) {
		R57_STAGE1_PROVISIONS = r57_STAGE1_PROVISIONS;
	}
	public BigDecimal getR57_QUALIFY_STAGE2_PROVISIONS() {
		return R57_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR57_QUALIFY_STAGE2_PROVISIONS(BigDecimal r57_QUALIFY_STAGE2_PROVISIONS) {
		R57_QUALIFY_STAGE2_PROVISIONS = r57_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR57_TOTAL_GENERAL_PROVISIONS() {
		return R57_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR57_TOTAL_GENERAL_PROVISIONS(BigDecimal r57_TOTAL_GENERAL_PROVISIONS) {
		R57_TOTAL_GENERAL_PROVISIONS = r57_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR58_PRODUCT() {
		return R58_PRODUCT;
	}
	public void setR58_PRODUCT(String r58_PRODUCT) {
		R58_PRODUCT = r58_PRODUCT;
	}
	public BigDecimal getR58_STAGE1_PROVISIONS() {
		return R58_STAGE1_PROVISIONS;
	}
	public void setR58_STAGE1_PROVISIONS(BigDecimal r58_STAGE1_PROVISIONS) {
		R58_STAGE1_PROVISIONS = r58_STAGE1_PROVISIONS;
	}
	public BigDecimal getR58_QUALIFY_STAGE2_PROVISIONS() {
		return R58_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR58_QUALIFY_STAGE2_PROVISIONS(BigDecimal r58_QUALIFY_STAGE2_PROVISIONS) {
		R58_QUALIFY_STAGE2_PROVISIONS = r58_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR58_TOTAL_GENERAL_PROVISIONS() {
		return R58_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR58_TOTAL_GENERAL_PROVISIONS(BigDecimal r58_TOTAL_GENERAL_PROVISIONS) {
		R58_TOTAL_GENERAL_PROVISIONS = r58_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR59_PRODUCT() {
		return R59_PRODUCT;
	}
	public void setR59_PRODUCT(String r59_PRODUCT) {
		R59_PRODUCT = r59_PRODUCT;
	}
	public BigDecimal getR59_STAGE1_PROVISIONS() {
		return R59_STAGE1_PROVISIONS;
	}
	public void setR59_STAGE1_PROVISIONS(BigDecimal r59_STAGE1_PROVISIONS) {
		R59_STAGE1_PROVISIONS = r59_STAGE1_PROVISIONS;
	}
	public BigDecimal getR59_QUALIFY_STAGE2_PROVISIONS() {
		return R59_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR59_QUALIFY_STAGE2_PROVISIONS(BigDecimal r59_QUALIFY_STAGE2_PROVISIONS) {
		R59_QUALIFY_STAGE2_PROVISIONS = r59_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR59_TOTAL_GENERAL_PROVISIONS() {
		return R59_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR59_TOTAL_GENERAL_PROVISIONS(BigDecimal r59_TOTAL_GENERAL_PROVISIONS) {
		R59_TOTAL_GENERAL_PROVISIONS = r59_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR60_PRODUCT() {
		return R60_PRODUCT;
	}
	public void setR60_PRODUCT(String r60_PRODUCT) {
		R60_PRODUCT = r60_PRODUCT;
	}
	public BigDecimal getR60_STAGE1_PROVISIONS() {
		return R60_STAGE1_PROVISIONS;
	}
	public void setR60_STAGE1_PROVISIONS(BigDecimal r60_STAGE1_PROVISIONS) {
		R60_STAGE1_PROVISIONS = r60_STAGE1_PROVISIONS;
	}
	public BigDecimal getR60_QUALIFY_STAGE2_PROVISIONS() {
		return R60_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR60_QUALIFY_STAGE2_PROVISIONS(BigDecimal r60_QUALIFY_STAGE2_PROVISIONS) {
		R60_QUALIFY_STAGE2_PROVISIONS = r60_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR60_TOTAL_GENERAL_PROVISIONS() {
		return R60_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR60_TOTAL_GENERAL_PROVISIONS(BigDecimal r60_TOTAL_GENERAL_PROVISIONS) {
		R60_TOTAL_GENERAL_PROVISIONS = r60_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR61_PRODUCT() {
		return R61_PRODUCT;
	}
	public void setR61_PRODUCT(String r61_PRODUCT) {
		R61_PRODUCT = r61_PRODUCT;
	}
	public BigDecimal getR61_STAGE1_PROVISIONS() {
		return R61_STAGE1_PROVISIONS;
	}
	public void setR61_STAGE1_PROVISIONS(BigDecimal r61_STAGE1_PROVISIONS) {
		R61_STAGE1_PROVISIONS = r61_STAGE1_PROVISIONS;
	}
	public BigDecimal getR61_QUALIFY_STAGE2_PROVISIONS() {
		return R61_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR61_QUALIFY_STAGE2_PROVISIONS(BigDecimal r61_QUALIFY_STAGE2_PROVISIONS) {
		R61_QUALIFY_STAGE2_PROVISIONS = r61_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR61_TOTAL_GENERAL_PROVISIONS() {
		return R61_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR61_TOTAL_GENERAL_PROVISIONS(BigDecimal r61_TOTAL_GENERAL_PROVISIONS) {
		R61_TOTAL_GENERAL_PROVISIONS = r61_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR62_PRODUCT() {
		return R62_PRODUCT;
	}
	public void setR62_PRODUCT(String r62_PRODUCT) {
		R62_PRODUCT = r62_PRODUCT;
	}
	public BigDecimal getR62_STAGE1_PROVISIONS() {
		return R62_STAGE1_PROVISIONS;
	}
	public void setR62_STAGE1_PROVISIONS(BigDecimal r62_STAGE1_PROVISIONS) {
		R62_STAGE1_PROVISIONS = r62_STAGE1_PROVISIONS;
	}
	public BigDecimal getR62_QUALIFY_STAGE2_PROVISIONS() {
		return R62_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR62_QUALIFY_STAGE2_PROVISIONS(BigDecimal r62_QUALIFY_STAGE2_PROVISIONS) {
		R62_QUALIFY_STAGE2_PROVISIONS = r62_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR62_TOTAL_GENERAL_PROVISIONS() {
		return R62_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR62_TOTAL_GENERAL_PROVISIONS(BigDecimal r62_TOTAL_GENERAL_PROVISIONS) {
		R62_TOTAL_GENERAL_PROVISIONS = r62_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR63_PRODUCT() {
		return R63_PRODUCT;
	}
	public void setR63_PRODUCT(String r63_PRODUCT) {
		R63_PRODUCT = r63_PRODUCT;
	}
	public BigDecimal getR63_STAGE1_PROVISIONS() {
		return R63_STAGE1_PROVISIONS;
	}
	public void setR63_STAGE1_PROVISIONS(BigDecimal r63_STAGE1_PROVISIONS) {
		R63_STAGE1_PROVISIONS = r63_STAGE1_PROVISIONS;
	}
	public BigDecimal getR63_QUALIFY_STAGE2_PROVISIONS() {
		return R63_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR63_QUALIFY_STAGE2_PROVISIONS(BigDecimal r63_QUALIFY_STAGE2_PROVISIONS) {
		R63_QUALIFY_STAGE2_PROVISIONS = r63_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR63_TOTAL_GENERAL_PROVISIONS() {
		return R63_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR63_TOTAL_GENERAL_PROVISIONS(BigDecimal r63_TOTAL_GENERAL_PROVISIONS) {
		R63_TOTAL_GENERAL_PROVISIONS = r63_TOTAL_GENERAL_PROVISIONS;
	}
	public String getR64_PRODUCT() {
		return R64_PRODUCT;
	}
	public void setR64_PRODUCT(String r64_PRODUCT) {
		R64_PRODUCT = r64_PRODUCT;
	}
	public BigDecimal getR64_STAGE1_PROVISIONS() {
		return R64_STAGE1_PROVISIONS;
	}
	public void setR64_STAGE1_PROVISIONS(BigDecimal r64_STAGE1_PROVISIONS) {
		R64_STAGE1_PROVISIONS = r64_STAGE1_PROVISIONS;
	}
	public BigDecimal getR64_QUALIFY_STAGE2_PROVISIONS() {
		return R64_QUALIFY_STAGE2_PROVISIONS;
	}
	public void setR64_QUALIFY_STAGE2_PROVISIONS(BigDecimal r64_QUALIFY_STAGE2_PROVISIONS) {
		R64_QUALIFY_STAGE2_PROVISIONS = r64_QUALIFY_STAGE2_PROVISIONS;
	}
	public BigDecimal getR64_TOTAL_GENERAL_PROVISIONS() {
		return R64_TOTAL_GENERAL_PROVISIONS;
	}
	public void setR64_TOTAL_GENERAL_PROVISIONS(BigDecimal r64_TOTAL_GENERAL_PROVISIONS) {
		R64_TOTAL_GENERAL_PROVISIONS = r64_TOTAL_GENERAL_PROVISIONS;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public String getREPORT_VERSION() {
		return REPORT_VERSION;
	}
	public void setREPORT_VERSION(String rEPORT_VERSION) {
		REPORT_VERSION = rEPORT_VERSION;
	}
	public String getREPORT_FREQUENCY() {
		return REPORT_FREQUENCY;
	}
	public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
		REPORT_FREQUENCY = rEPORT_FREQUENCY;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_DESC() {
		return REPORT_DESC;
	}
	public void setREPORT_DESC(String rEPORT_DESC) {
		REPORT_DESC = rEPORT_DESC;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	public M_GP_Summary_Entity() {
		super();
		// TODO Auto-generated constructor stub
	}
}
