package com.bornfire.brrs.entities;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
@Entity
@Table(name = "BRRS_M_SRWA_12D_DETAILTABLE")
public class M_SRWA_12D_Detail_Entity {
	private BigDecimal R12_LINE_NO_EXCHANGE_CONTRACTS;
    private String R12_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
    private BigDecimal R12_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
    private BigDecimal R12_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
    private BigDecimal R12_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
    private BigDecimal R12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
    private BigDecimal R12_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
    private BigDecimal R12_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
    private BigDecimal R12_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
    private BigDecimal R12_LINE_NO_INTEREST_CONTRACTS;
    private String R12_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
    private BigDecimal R12_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
    private BigDecimal R12_TOTAL_CURRENT_INTEREST_CONTRACTS;
    private BigDecimal R12_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
    private BigDecimal R12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
    private BigDecimal R12_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
    private BigDecimal R12_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
    private BigDecimal R12_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
    private BigDecimal R13_LINE_NO_EXCHANGE_CONTRACTS;
    private String R13_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
    private BigDecimal R13_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
    private BigDecimal R13_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
    private BigDecimal R13_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
    private BigDecimal R13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
    private BigDecimal R13_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
    private BigDecimal R13_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
    private BigDecimal R13_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
    private BigDecimal R13_LINE_NO_INTEREST_CONTRACTS;
    private String R13_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
    private BigDecimal R13_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
    private BigDecimal R13_TOTAL_CURRENT_INTEREST_CONTRACTS;
    private BigDecimal R13_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
    private BigDecimal R13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
    private BigDecimal R13_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
    private BigDecimal R13_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
    private BigDecimal R13_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
    private BigDecimal R14_LINE_NO_EXCHANGE_CONTRACTS;
    private String R14_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
    private BigDecimal R14_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
    private BigDecimal R14_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
    private BigDecimal R14_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
    private BigDecimal R14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
    private BigDecimal R14_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
    private BigDecimal R14_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
    private BigDecimal R14_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
    private BigDecimal R14_LINE_NO_INTEREST_CONTRACTS;
    private String R14_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
    private BigDecimal R14_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
    private BigDecimal R14_TOTAL_CURRENT_INTEREST_CONTRACTS;
    private BigDecimal R14_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
    private BigDecimal R14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
    private BigDecimal R14_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
    private BigDecimal R14_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
    private BigDecimal R14_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
    private BigDecimal R15_LINE_NO_EXCHANGE_CONTRACTS;
    private String R15_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
    private BigDecimal R15_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
    private BigDecimal R15_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
    private BigDecimal R15_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
    private BigDecimal R15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
    private BigDecimal R15_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
    private BigDecimal R15_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
    private BigDecimal R15_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
    private BigDecimal R15_LINE_NO_INTEREST_CONTRACTS;
    private String R15_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
    private BigDecimal R15_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
    private BigDecimal R15_TOTAL_CURRENT_INTEREST_CONTRACTS;
    private BigDecimal R15_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
    private BigDecimal R15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
    private BigDecimal R15_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
    private BigDecimal R15_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
    private BigDecimal R15_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
    private BigDecimal R21_LINE_NO_EQUITY_CONTRACTS;
    private String R21_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
    private BigDecimal R21_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
    private BigDecimal R21_TOTAL_CURRENT_EQUITY_CONTRACTS;
    private BigDecimal R21_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
    private BigDecimal R21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
    private BigDecimal R21_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
    private BigDecimal R21_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
    private BigDecimal R21_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
    private BigDecimal R21_LINE_NO_PRECIOUS_CONTRACTS;
    private String R21_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
    private BigDecimal R21_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
    private BigDecimal R21_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
    private BigDecimal R21_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
    private BigDecimal R21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
    private BigDecimal R21_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
    private BigDecimal R21_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
    private BigDecimal R21_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
    private BigDecimal R22_LINE_NO_EQUITY_CONTRACTS;
    private String R22_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
    private BigDecimal R22_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
    private BigDecimal R22_TOTAL_CURRENT_EQUITY_CONTRACTS;
    private BigDecimal R22_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
    private BigDecimal R22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
    private BigDecimal R22_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
    private BigDecimal R22_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
    private BigDecimal R22_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
    private BigDecimal R22_LINE_NO_PRECIOUS_CONTRACTS;
    private String R22_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
    private BigDecimal R22_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
    private BigDecimal R22_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
    private BigDecimal R22_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
    private BigDecimal R22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
    private BigDecimal R22_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
    private BigDecimal R22_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
    private BigDecimal R22_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
    private BigDecimal R23_LINE_NO_EQUITY_CONTRACTS;
    private String R23_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
    private BigDecimal R23_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
    private BigDecimal R23_TOTAL_CURRENT_EQUITY_CONTRACTS;
    private BigDecimal R23_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
    private BigDecimal R23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
    private BigDecimal R23_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
    private BigDecimal R23_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
    private BigDecimal R23_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
    private BigDecimal R23_LINE_NO_PRECIOUS_CONTRACTS;
    private String R23_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
    private BigDecimal R23_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
    private BigDecimal R23_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
    private BigDecimal R23_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
    private BigDecimal R23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
    private BigDecimal R23_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
    private BigDecimal R23_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
    private BigDecimal R23_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
    private BigDecimal R24_LINE_NO_EQUITY_CONTRACTS;
    private String R24_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
    private BigDecimal R24_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
    private BigDecimal R24_TOTAL_CURRENT_EQUITY_CONTRACTS;
    private BigDecimal R24_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
    private BigDecimal R24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
    private BigDecimal R24_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
    private BigDecimal R24_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
    private BigDecimal R24_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
    private BigDecimal R24_LINE_NO_PRECIOUS_CONTRACTS;
    private String R24_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
    private BigDecimal R24_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
    private BigDecimal R24_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
    private BigDecimal R24_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
    private BigDecimal R24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
    private BigDecimal R24_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
    private BigDecimal R24_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
    private BigDecimal R24_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
    private BigDecimal R30_LINE_NO_DEBT_CONTRACTS;
    private String R30_RESIDUAL_MATURITY_DEBT_CONTRACTS;
    private BigDecimal R30_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
    private BigDecimal R30_TOTAL_CURRENT_DEBT_CONTRACTS;
    private BigDecimal R30_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
    private BigDecimal R30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
    private BigDecimal R30_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
    private BigDecimal R30_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
    private BigDecimal R30_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
    private BigDecimal R30_LINE_NO_CREDIT_CONTRACTS;
    private String R30_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
    private BigDecimal R30_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
    private BigDecimal R30_TOTAL_CURRENT_CREDIT_CONTRACTS;
    private BigDecimal R30_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
    private BigDecimal R30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
    private BigDecimal R30_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
    private BigDecimal R30_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
    private BigDecimal R30_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
    private BigDecimal R31_LINE_NO_DEBT_CONTRACTS;
    private String R31_RESIDUAL_MATURITY_DEBT_CONTRACTS;
    private BigDecimal R31_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
    private BigDecimal R31_TOTAL_CURRENT_DEBT_CONTRACTS;
    private BigDecimal R31_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
    private BigDecimal R31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
    private BigDecimal R31_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
    private BigDecimal R31_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
    private BigDecimal R31_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
    private BigDecimal R31_LINE_NO_CREDIT_CONTRACTS;
    private String R31_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
    private BigDecimal R31_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
    private BigDecimal R31_TOTAL_CURRENT_CREDIT_CONTRACTS;
    private BigDecimal R31_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
    private BigDecimal R31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
    private BigDecimal R31_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
    private BigDecimal R31_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
    private BigDecimal R31_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
    private BigDecimal R32_LINE_NO_DEBT_CONTRACTS;
    private String R32_RESIDUAL_MATURITY_DEBT_CONTRACTS;
    private BigDecimal R32_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
    private BigDecimal R32_TOTAL_CURRENT_DEBT_CONTRACTS;
    private BigDecimal R32_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
    private BigDecimal R32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
    private BigDecimal R32_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
    private BigDecimal R32_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
    private BigDecimal R32_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
    private BigDecimal R32_LINE_NO_CREDIT_CONTRACTS;
    private String R32_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
    private BigDecimal R32_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
    private BigDecimal R32_TOTAL_CURRENT_CREDIT_CONTRACTS;
    private BigDecimal R32_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
    private BigDecimal R32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
    private BigDecimal R32_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
    private BigDecimal R32_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
    private BigDecimal R32_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
    private BigDecimal R33_LINE_NO_DEBT_CONTRACTS;
    private String R33_RESIDUAL_MATURITY_DEBT_CONTRACTS;
    private BigDecimal R33_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
    private BigDecimal R33_TOTAL_CURRENT_DEBT_CONTRACTS;
    private BigDecimal R33_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
    private BigDecimal R33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
    private BigDecimal R33_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
    private BigDecimal R33_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
    private BigDecimal R33_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
    private BigDecimal R33_LINE_NO_CREDIT_CONTRACTS;
    private String R33_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
    private BigDecimal R33_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
    private BigDecimal R33_TOTAL_CURRENT_CREDIT_CONTRACTS;
    private BigDecimal R33_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
    private BigDecimal R33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
    private BigDecimal R33_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
    private BigDecimal R33_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
    private BigDecimal R33_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
    private BigDecimal R43_LINE_NO_DERIVATIVE_CONTRACTS;
    private String R43_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
    private BigDecimal R43_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
    private BigDecimal R43_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
    private BigDecimal R43_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
    private BigDecimal R43_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
    private BigDecimal R43_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
    private BigDecimal R43_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
    private BigDecimal R44_LINE_NO_DERIVATIVE_CONTRACTS;
    private String R44_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
    private BigDecimal R44_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
    private BigDecimal R44_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
    private BigDecimal R44_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
    private BigDecimal R44_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
    private BigDecimal R44_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
    private BigDecimal R44_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
    private BigDecimal R45_LINE_NO_DERIVATIVE_CONTRACTS;
    private String R45_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
    private BigDecimal R45_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
    private BigDecimal R45_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
    private BigDecimal R45_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
    private BigDecimal R45_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
    private BigDecimal R45_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
    private BigDecimal R45_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
    
    @Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date report_date;
	private BigDecimal report_version;
	private String report_frequency;
	private String report_code;
	private String report_desc;
	private String entity_flg;
	private String modify_flg;
	private String del_flg;
	public BigDecimal getR12_LINE_NO_EXCHANGE_CONTRACTS() {
		return R12_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public void setR12_LINE_NO_EXCHANGE_CONTRACTS(BigDecimal r12_LINE_NO_EXCHANGE_CONTRACTS) {
		R12_LINE_NO_EXCHANGE_CONTRACTS = r12_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public String getR12_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS() {
		return R12_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public void setR12_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS(String r12_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS) {
		R12_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS = r12_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS() {
		return R12_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public void setR12_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS(BigDecimal r12_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS) {
		R12_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS = r12_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_TOTAL_CURRENT_EXCHANGE_CONTRACTS() {
		return R12_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public void setR12_TOTAL_CURRENT_EXCHANGE_CONTRACTS(BigDecimal r12_TOTAL_CURRENT_EXCHANGE_CONTRACTS) {
		R12_TOTAL_CURRENT_EXCHANGE_CONTRACTS = r12_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS() {
		return R12_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public void setR12_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS(
			BigDecimal r12_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS) {
		R12_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS = r12_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS() {
		return R12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public void setR12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS(
			BigDecimal r12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS) {
		R12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS = r12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS() {
		return R12_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public void setR12_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS(BigDecimal r12_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS) {
		R12_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS = r12_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS() {
		return R12_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public void setR12_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS(
			BigDecimal r12_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS) {
		R12_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS = r12_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS() {
		return R12_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public void setR12_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS(BigDecimal r12_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS) {
		R12_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS = r12_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR12_LINE_NO_INTEREST_CONTRACTS() {
		return R12_LINE_NO_INTEREST_CONTRACTS;
	}
	public void setR12_LINE_NO_INTEREST_CONTRACTS(BigDecimal r12_LINE_NO_INTEREST_CONTRACTS) {
		R12_LINE_NO_INTEREST_CONTRACTS = r12_LINE_NO_INTEREST_CONTRACTS;
	}
	public String getR12_RESIDUAL_MATURITY_INTEREST_CONTRACTS() {
		return R12_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public void setR12_RESIDUAL_MATURITY_INTEREST_CONTRACTS(String r12_RESIDUAL_MATURITY_INTEREST_CONTRACTS) {
		R12_RESIDUAL_MATURITY_INTEREST_CONTRACTS = r12_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR12_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS() {
		return R12_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public void setR12_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS(BigDecimal r12_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS) {
		R12_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS = r12_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR12_TOTAL_CURRENT_INTEREST_CONTRACTS() {
		return R12_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public void setR12_TOTAL_CURRENT_INTEREST_CONTRACTS(BigDecimal r12_TOTAL_CURRENT_INTEREST_CONTRACTS) {
		R12_TOTAL_CURRENT_INTEREST_CONTRACTS = r12_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR12_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS() {
		return R12_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public void setR12_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS(
			BigDecimal r12_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS) {
		R12_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS = r12_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS() {
		return R12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public void setR12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS(
			BigDecimal r12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS) {
		R12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS = r12_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public BigDecimal getR12_CREDIT_EQUIVALENT_INTEREST_CONTRACTS() {
		return R12_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public void setR12_CREDIT_EQUIVALENT_INTEREST_CONTRACTS(BigDecimal r12_CREDIT_EQUIVALENT_INTEREST_CONTRACTS) {
		R12_CREDIT_EQUIVALENT_INTEREST_CONTRACTS = r12_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR12_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS() {
		return R12_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public void setR12_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS(
			BigDecimal r12_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS) {
		R12_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS = r12_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR12_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS() {
		return R12_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public void setR12_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS(BigDecimal r12_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS) {
		R12_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS = r12_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_LINE_NO_EXCHANGE_CONTRACTS() {
		return R13_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public void setR13_LINE_NO_EXCHANGE_CONTRACTS(BigDecimal r13_LINE_NO_EXCHANGE_CONTRACTS) {
		R13_LINE_NO_EXCHANGE_CONTRACTS = r13_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public String getR13_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS() {
		return R13_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public void setR13_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS(String r13_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS) {
		R13_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS = r13_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS() {
		return R13_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public void setR13_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS(BigDecimal r13_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS) {
		R13_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS = r13_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_TOTAL_CURRENT_EXCHANGE_CONTRACTS() {
		return R13_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public void setR13_TOTAL_CURRENT_EXCHANGE_CONTRACTS(BigDecimal r13_TOTAL_CURRENT_EXCHANGE_CONTRACTS) {
		R13_TOTAL_CURRENT_EXCHANGE_CONTRACTS = r13_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS() {
		return R13_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public void setR13_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS(
			BigDecimal r13_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS) {
		R13_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS = r13_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS() {
		return R13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public void setR13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS(
			BigDecimal r13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS) {
		R13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS = r13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS() {
		return R13_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public void setR13_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS(BigDecimal r13_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS) {
		R13_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS = r13_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS() {
		return R13_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public void setR13_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS(
			BigDecimal r13_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS) {
		R13_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS = r13_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS() {
		return R13_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public void setR13_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS(BigDecimal r13_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS) {
		R13_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS = r13_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR13_LINE_NO_INTEREST_CONTRACTS() {
		return R13_LINE_NO_INTEREST_CONTRACTS;
	}
	public void setR13_LINE_NO_INTEREST_CONTRACTS(BigDecimal r13_LINE_NO_INTEREST_CONTRACTS) {
		R13_LINE_NO_INTEREST_CONTRACTS = r13_LINE_NO_INTEREST_CONTRACTS;
	}
	public String getR13_RESIDUAL_MATURITY_INTEREST_CONTRACTS() {
		return R13_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public void setR13_RESIDUAL_MATURITY_INTEREST_CONTRACTS(String r13_RESIDUAL_MATURITY_INTEREST_CONTRACTS) {
		R13_RESIDUAL_MATURITY_INTEREST_CONTRACTS = r13_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS() {
		return R13_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public void setR13_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS(BigDecimal r13_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS) {
		R13_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS = r13_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_TOTAL_CURRENT_INTEREST_CONTRACTS() {
		return R13_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public void setR13_TOTAL_CURRENT_INTEREST_CONTRACTS(BigDecimal r13_TOTAL_CURRENT_INTEREST_CONTRACTS) {
		R13_TOTAL_CURRENT_INTEREST_CONTRACTS = r13_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS() {
		return R13_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public void setR13_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS(
			BigDecimal r13_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS) {
		R13_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS = r13_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS() {
		return R13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public void setR13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS(
			BigDecimal r13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS) {
		R13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS = r13_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_CREDIT_EQUIVALENT_INTEREST_CONTRACTS() {
		return R13_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public void setR13_CREDIT_EQUIVALENT_INTEREST_CONTRACTS(BigDecimal r13_CREDIT_EQUIVALENT_INTEREST_CONTRACTS) {
		R13_CREDIT_EQUIVALENT_INTEREST_CONTRACTS = r13_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS() {
		return R13_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public void setR13_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS(
			BigDecimal r13_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS) {
		R13_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS = r13_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR13_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS() {
		return R13_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public void setR13_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS(BigDecimal r13_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS) {
		R13_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS = r13_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_LINE_NO_EXCHANGE_CONTRACTS() {
		return R14_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public void setR14_LINE_NO_EXCHANGE_CONTRACTS(BigDecimal r14_LINE_NO_EXCHANGE_CONTRACTS) {
		R14_LINE_NO_EXCHANGE_CONTRACTS = r14_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public String getR14_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS() {
		return R14_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public void setR14_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS(String r14_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS) {
		R14_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS = r14_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS() {
		return R14_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public void setR14_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS(BigDecimal r14_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS) {
		R14_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS = r14_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_TOTAL_CURRENT_EXCHANGE_CONTRACTS() {
		return R14_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public void setR14_TOTAL_CURRENT_EXCHANGE_CONTRACTS(BigDecimal r14_TOTAL_CURRENT_EXCHANGE_CONTRACTS) {
		R14_TOTAL_CURRENT_EXCHANGE_CONTRACTS = r14_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS() {
		return R14_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public void setR14_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS(
			BigDecimal r14_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS) {
		R14_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS = r14_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS() {
		return R14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public void setR14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS(
			BigDecimal r14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS) {
		R14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS = r14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS() {
		return R14_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public void setR14_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS(BigDecimal r14_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS) {
		R14_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS = r14_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS() {
		return R14_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public void setR14_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS(
			BigDecimal r14_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS) {
		R14_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS = r14_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS() {
		return R14_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public void setR14_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS(BigDecimal r14_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS) {
		R14_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS = r14_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR14_LINE_NO_INTEREST_CONTRACTS() {
		return R14_LINE_NO_INTEREST_CONTRACTS;
	}
	public void setR14_LINE_NO_INTEREST_CONTRACTS(BigDecimal r14_LINE_NO_INTEREST_CONTRACTS) {
		R14_LINE_NO_INTEREST_CONTRACTS = r14_LINE_NO_INTEREST_CONTRACTS;
	}
	public String getR14_RESIDUAL_MATURITY_INTEREST_CONTRACTS() {
		return R14_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public void setR14_RESIDUAL_MATURITY_INTEREST_CONTRACTS(String r14_RESIDUAL_MATURITY_INTEREST_CONTRACTS) {
		R14_RESIDUAL_MATURITY_INTEREST_CONTRACTS = r14_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS() {
		return R14_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public void setR14_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS(BigDecimal r14_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS) {
		R14_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS = r14_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_TOTAL_CURRENT_INTEREST_CONTRACTS() {
		return R14_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public void setR14_TOTAL_CURRENT_INTEREST_CONTRACTS(BigDecimal r14_TOTAL_CURRENT_INTEREST_CONTRACTS) {
		R14_TOTAL_CURRENT_INTEREST_CONTRACTS = r14_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS() {
		return R14_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public void setR14_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS(
			BigDecimal r14_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS) {
		R14_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS = r14_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS() {
		return R14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public void setR14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS(
			BigDecimal r14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS) {
		R14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS = r14_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_CREDIT_EQUIVALENT_INTEREST_CONTRACTS() {
		return R14_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public void setR14_CREDIT_EQUIVALENT_INTEREST_CONTRACTS(BigDecimal r14_CREDIT_EQUIVALENT_INTEREST_CONTRACTS) {
		R14_CREDIT_EQUIVALENT_INTEREST_CONTRACTS = r14_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS() {
		return R14_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public void setR14_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS(
			BigDecimal r14_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS) {
		R14_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS = r14_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR14_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS() {
		return R14_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public void setR14_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS(BigDecimal r14_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS) {
		R14_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS = r14_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_LINE_NO_EXCHANGE_CONTRACTS() {
		return R15_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public void setR15_LINE_NO_EXCHANGE_CONTRACTS(BigDecimal r15_LINE_NO_EXCHANGE_CONTRACTS) {
		R15_LINE_NO_EXCHANGE_CONTRACTS = r15_LINE_NO_EXCHANGE_CONTRACTS;
	}
	public String getR15_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS() {
		return R15_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public void setR15_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS(String r15_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS) {
		R15_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS = r15_RESIDUAL_MATURITY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS() {
		return R15_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public void setR15_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS(BigDecimal r15_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS) {
		R15_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS = r15_PRINCIPAL_AMOUNT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_TOTAL_CURRENT_EXCHANGE_CONTRACTS() {
		return R15_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public void setR15_TOTAL_CURRENT_EXCHANGE_CONTRACTS(BigDecimal r15_TOTAL_CURRENT_EXCHANGE_CONTRACTS) {
		R15_TOTAL_CURRENT_EXCHANGE_CONTRACTS = r15_TOTAL_CURRENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS() {
		return R15_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public void setR15_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS(
			BigDecimal r15_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS) {
		R15_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS = r15_POTENTIAL_FUTURE_CREDIT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS() {
		return R15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public void setR15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS(
			BigDecimal r15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS) {
		R15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS = r15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS() {
		return R15_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public void setR15_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS(BigDecimal r15_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS) {
		R15_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS = r15_CREDIT_EQUIVALENT_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS() {
		return R15_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public void setR15_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS(
			BigDecimal r15_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS) {
		R15_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS = r15_APPLICABLE_COUNTERPARTY_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS() {
		return R15_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public void setR15_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS(BigDecimal r15_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS) {
		R15_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS = r15_RISK_WEIGHTED_ASSET_EXCHANGE_CONTRACTS;
	}
	public BigDecimal getR15_LINE_NO_INTEREST_CONTRACTS() {
		return R15_LINE_NO_INTEREST_CONTRACTS;
	}
	public void setR15_LINE_NO_INTEREST_CONTRACTS(BigDecimal r15_LINE_NO_INTEREST_CONTRACTS) {
		R15_LINE_NO_INTEREST_CONTRACTS = r15_LINE_NO_INTEREST_CONTRACTS;
	}
	public String getR15_RESIDUAL_MATURITY_INTEREST_CONTRACTS() {
		return R15_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public void setR15_RESIDUAL_MATURITY_INTEREST_CONTRACTS(String r15_RESIDUAL_MATURITY_INTEREST_CONTRACTS) {
		R15_RESIDUAL_MATURITY_INTEREST_CONTRACTS = r15_RESIDUAL_MATURITY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS() {
		return R15_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public void setR15_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS(BigDecimal r15_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS) {
		R15_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS = r15_PRINCIPAL_AMOUNT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_TOTAL_CURRENT_INTEREST_CONTRACTS() {
		return R15_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public void setR15_TOTAL_CURRENT_INTEREST_CONTRACTS(BigDecimal r15_TOTAL_CURRENT_INTEREST_CONTRACTS) {
		R15_TOTAL_CURRENT_INTEREST_CONTRACTS = r15_TOTAL_CURRENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS() {
		return R15_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public void setR15_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS(
			BigDecimal r15_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS) {
		R15_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS = r15_POTENTIAL_FUTURE_CREDIT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS() {
		return R15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public void setR15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS(
			BigDecimal r15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS) {
		R15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS = r15_POTENTIAL_FUTURE_CREDIT_EXPOSURE_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_CREDIT_EQUIVALENT_INTEREST_CONTRACTS() {
		return R15_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public void setR15_CREDIT_EQUIVALENT_INTEREST_CONTRACTS(BigDecimal r15_CREDIT_EQUIVALENT_INTEREST_CONTRACTS) {
		R15_CREDIT_EQUIVALENT_INTEREST_CONTRACTS = r15_CREDIT_EQUIVALENT_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS() {
		return R15_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public void setR15_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS(
			BigDecimal r15_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS) {
		R15_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS = r15_APPLICABLE_COUNTERPARTY_INTEREST_CONTRACTS;
	}
	public BigDecimal getR15_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS() {
		return R15_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public void setR15_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS(BigDecimal r15_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS) {
		R15_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS = r15_RISK_WEIGHTED_ASSET_INTEREST_CONTRACTS;
	}
	public BigDecimal getR21_LINE_NO_EQUITY_CONTRACTS() {
		return R21_LINE_NO_EQUITY_CONTRACTS;
	}
	public void setR21_LINE_NO_EQUITY_CONTRACTS(BigDecimal r21_LINE_NO_EQUITY_CONTRACTS) {
		R21_LINE_NO_EQUITY_CONTRACTS = r21_LINE_NO_EQUITY_CONTRACTS;
	}
	public String getR21_RESIDUAL_MATURITY_EQUITY_CONTRACTS() {
		return R21_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public void setR21_RESIDUAL_MATURITY_EQUITY_CONTRACTS(String r21_RESIDUAL_MATURITY_EQUITY_CONTRACTS) {
		R21_RESIDUAL_MATURITY_EQUITY_CONTRACTS = r21_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS() {
		return R21_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public void setR21_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS(BigDecimal r21_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS) {
		R21_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS = r21_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_TOTAL_CURRENT_EQUITY_CONTRACTS() {
		return R21_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public void setR21_TOTAL_CURRENT_EQUITY_CONTRACTS(BigDecimal r21_TOTAL_CURRENT_EQUITY_CONTRACTS) {
		R21_TOTAL_CURRENT_EQUITY_CONTRACTS = r21_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS() {
		return R21_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public void setR21_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS(BigDecimal r21_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS) {
		R21_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS = r21_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS() {
		return R21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public void setR21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS(
			BigDecimal r21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS) {
		R21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS = r21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_CREDIT_EQUIVALENT_EQUITY_CONTRACTS() {
		return R21_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public void setR21_CREDIT_EQUIVALENT_EQUITY_CONTRACTS(BigDecimal r21_CREDIT_EQUIVALENT_EQUITY_CONTRACTS) {
		R21_CREDIT_EQUIVALENT_EQUITY_CONTRACTS = r21_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS() {
		return R21_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public void setR21_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS(BigDecimal r21_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS) {
		R21_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS = r21_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS() {
		return R21_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public void setR21_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS(BigDecimal r21_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS) {
		R21_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS = r21_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public BigDecimal getR21_LINE_NO_PRECIOUS_CONTRACTS() {
		return R21_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public void setR21_LINE_NO_PRECIOUS_CONTRACTS(BigDecimal r21_LINE_NO_PRECIOUS_CONTRACTS) {
		R21_LINE_NO_PRECIOUS_CONTRACTS = r21_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public String getR21_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS() {
		return R21_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public void setR21_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS(String r21_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS) {
		R21_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS = r21_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR21_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS() {
		return R21_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public void setR21_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS(BigDecimal r21_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS) {
		R21_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS = r21_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR21_TOTAL_CURRENT_PRECIOUS_CONTRACTS() {
		return R21_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public void setR21_TOTAL_CURRENT_PRECIOUS_CONTRACTS(BigDecimal r21_TOTAL_CURRENT_PRECIOUS_CONTRACTS) {
		R21_TOTAL_CURRENT_PRECIOUS_CONTRACTS = r21_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR21_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS() {
		return R21_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public void setR21_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS(
			BigDecimal r21_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS) {
		R21_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS = r21_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS() {
		return R21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public void setR21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS(
			BigDecimal r21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS) {
		R21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS = r21_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR21_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS() {
		return R21_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public void setR21_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS(BigDecimal r21_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS) {
		R21_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS = r21_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR21_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS() {
		return R21_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public void setR21_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS(
			BigDecimal r21_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS) {
		R21_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS = r21_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR21_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS() {
		return R21_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public void setR21_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS(BigDecimal r21_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS) {
		R21_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS = r21_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_LINE_NO_EQUITY_CONTRACTS() {
		return R22_LINE_NO_EQUITY_CONTRACTS;
	}
	public void setR22_LINE_NO_EQUITY_CONTRACTS(BigDecimal r22_LINE_NO_EQUITY_CONTRACTS) {
		R22_LINE_NO_EQUITY_CONTRACTS = r22_LINE_NO_EQUITY_CONTRACTS;
	}
	public String getR22_RESIDUAL_MATURITY_EQUITY_CONTRACTS() {
		return R22_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public void setR22_RESIDUAL_MATURITY_EQUITY_CONTRACTS(String r22_RESIDUAL_MATURITY_EQUITY_CONTRACTS) {
		R22_RESIDUAL_MATURITY_EQUITY_CONTRACTS = r22_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS() {
		return R22_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public void setR22_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS(BigDecimal r22_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS) {
		R22_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS = r22_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_TOTAL_CURRENT_EQUITY_CONTRACTS() {
		return R22_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public void setR22_TOTAL_CURRENT_EQUITY_CONTRACTS(BigDecimal r22_TOTAL_CURRENT_EQUITY_CONTRACTS) {
		R22_TOTAL_CURRENT_EQUITY_CONTRACTS = r22_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS() {
		return R22_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public void setR22_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS(BigDecimal r22_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS) {
		R22_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS = r22_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS() {
		return R22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public void setR22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS(
			BigDecimal r22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS) {
		R22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS = r22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_CREDIT_EQUIVALENT_EQUITY_CONTRACTS() {
		return R22_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public void setR22_CREDIT_EQUIVALENT_EQUITY_CONTRACTS(BigDecimal r22_CREDIT_EQUIVALENT_EQUITY_CONTRACTS) {
		R22_CREDIT_EQUIVALENT_EQUITY_CONTRACTS = r22_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS() {
		return R22_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public void setR22_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS(BigDecimal r22_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS) {
		R22_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS = r22_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS() {
		return R22_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public void setR22_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS(BigDecimal r22_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS) {
		R22_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS = r22_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public BigDecimal getR22_LINE_NO_PRECIOUS_CONTRACTS() {
		return R22_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public void setR22_LINE_NO_PRECIOUS_CONTRACTS(BigDecimal r22_LINE_NO_PRECIOUS_CONTRACTS) {
		R22_LINE_NO_PRECIOUS_CONTRACTS = r22_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public String getR22_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS() {
		return R22_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public void setR22_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS(String r22_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS) {
		R22_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS = r22_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS() {
		return R22_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public void setR22_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS(BigDecimal r22_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS) {
		R22_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS = r22_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_TOTAL_CURRENT_PRECIOUS_CONTRACTS() {
		return R22_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public void setR22_TOTAL_CURRENT_PRECIOUS_CONTRACTS(BigDecimal r22_TOTAL_CURRENT_PRECIOUS_CONTRACTS) {
		R22_TOTAL_CURRENT_PRECIOUS_CONTRACTS = r22_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS() {
		return R22_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public void setR22_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS(
			BigDecimal r22_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS) {
		R22_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS = r22_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS() {
		return R22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public void setR22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS(
			BigDecimal r22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS) {
		R22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS = r22_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS() {
		return R22_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public void setR22_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS(BigDecimal r22_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS) {
		R22_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS = r22_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS() {
		return R22_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public void setR22_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS(
			BigDecimal r22_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS) {
		R22_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS = r22_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR22_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS() {
		return R22_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public void setR22_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS(BigDecimal r22_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS) {
		R22_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS = r22_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_LINE_NO_EQUITY_CONTRACTS() {
		return R23_LINE_NO_EQUITY_CONTRACTS;
	}
	public void setR23_LINE_NO_EQUITY_CONTRACTS(BigDecimal r23_LINE_NO_EQUITY_CONTRACTS) {
		R23_LINE_NO_EQUITY_CONTRACTS = r23_LINE_NO_EQUITY_CONTRACTS;
	}
	public String getR23_RESIDUAL_MATURITY_EQUITY_CONTRACTS() {
		return R23_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public void setR23_RESIDUAL_MATURITY_EQUITY_CONTRACTS(String r23_RESIDUAL_MATURITY_EQUITY_CONTRACTS) {
		R23_RESIDUAL_MATURITY_EQUITY_CONTRACTS = r23_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS() {
		return R23_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public void setR23_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS(BigDecimal r23_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS) {
		R23_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS = r23_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_TOTAL_CURRENT_EQUITY_CONTRACTS() {
		return R23_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public void setR23_TOTAL_CURRENT_EQUITY_CONTRACTS(BigDecimal r23_TOTAL_CURRENT_EQUITY_CONTRACTS) {
		R23_TOTAL_CURRENT_EQUITY_CONTRACTS = r23_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS() {
		return R23_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public void setR23_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS(BigDecimal r23_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS) {
		R23_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS = r23_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS() {
		return R23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public void setR23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS(
			BigDecimal r23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS) {
		R23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS = r23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_CREDIT_EQUIVALENT_EQUITY_CONTRACTS() {
		return R23_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public void setR23_CREDIT_EQUIVALENT_EQUITY_CONTRACTS(BigDecimal r23_CREDIT_EQUIVALENT_EQUITY_CONTRACTS) {
		R23_CREDIT_EQUIVALENT_EQUITY_CONTRACTS = r23_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS() {
		return R23_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public void setR23_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS(BigDecimal r23_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS) {
		R23_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS = r23_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS() {
		return R23_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public void setR23_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS(BigDecimal r23_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS) {
		R23_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS = r23_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public BigDecimal getR23_LINE_NO_PRECIOUS_CONTRACTS() {
		return R23_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public void setR23_LINE_NO_PRECIOUS_CONTRACTS(BigDecimal r23_LINE_NO_PRECIOUS_CONTRACTS) {
		R23_LINE_NO_PRECIOUS_CONTRACTS = r23_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public String getR23_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS() {
		return R23_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public void setR23_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS(String r23_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS) {
		R23_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS = r23_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS() {
		return R23_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public void setR23_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS(BigDecimal r23_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS) {
		R23_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS = r23_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_TOTAL_CURRENT_PRECIOUS_CONTRACTS() {
		return R23_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public void setR23_TOTAL_CURRENT_PRECIOUS_CONTRACTS(BigDecimal r23_TOTAL_CURRENT_PRECIOUS_CONTRACTS) {
		R23_TOTAL_CURRENT_PRECIOUS_CONTRACTS = r23_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS() {
		return R23_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public void setR23_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS(
			BigDecimal r23_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS) {
		R23_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS = r23_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS() {
		return R23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public void setR23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS(
			BigDecimal r23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS) {
		R23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS = r23_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS() {
		return R23_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public void setR23_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS(BigDecimal r23_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS) {
		R23_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS = r23_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS() {
		return R23_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public void setR23_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS(
			BigDecimal r23_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS) {
		R23_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS = r23_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR23_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS() {
		return R23_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public void setR23_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS(BigDecimal r23_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS) {
		R23_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS = r23_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_LINE_NO_EQUITY_CONTRACTS() {
		return R24_LINE_NO_EQUITY_CONTRACTS;
	}
	public void setR24_LINE_NO_EQUITY_CONTRACTS(BigDecimal r24_LINE_NO_EQUITY_CONTRACTS) {
		R24_LINE_NO_EQUITY_CONTRACTS = r24_LINE_NO_EQUITY_CONTRACTS;
	}
	public String getR24_RESIDUAL_MATURITY_EQUITY_CONTRACTS() {
		return R24_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public void setR24_RESIDUAL_MATURITY_EQUITY_CONTRACTS(String r24_RESIDUAL_MATURITY_EQUITY_CONTRACTS) {
		R24_RESIDUAL_MATURITY_EQUITY_CONTRACTS = r24_RESIDUAL_MATURITY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS() {
		return R24_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public void setR24_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS(BigDecimal r24_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS) {
		R24_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS = r24_PRINCIPAL_AMOUNT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_TOTAL_CURRENT_EQUITY_CONTRACTS() {
		return R24_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public void setR24_TOTAL_CURRENT_EQUITY_CONTRACTS(BigDecimal r24_TOTAL_CURRENT_EQUITY_CONTRACTS) {
		R24_TOTAL_CURRENT_EQUITY_CONTRACTS = r24_TOTAL_CURRENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS() {
		return R24_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public void setR24_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS(BigDecimal r24_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS) {
		R24_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS = r24_POTENTIAL_FUTURE_CREDIT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS() {
		return R24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public void setR24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS(
			BigDecimal r24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS) {
		R24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS = r24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_CREDIT_EQUIVALENT_EQUITY_CONTRACTS() {
		return R24_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public void setR24_CREDIT_EQUIVALENT_EQUITY_CONTRACTS(BigDecimal r24_CREDIT_EQUIVALENT_EQUITY_CONTRACTS) {
		R24_CREDIT_EQUIVALENT_EQUITY_CONTRACTS = r24_CREDIT_EQUIVALENT_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS() {
		return R24_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public void setR24_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS(BigDecimal r24_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS) {
		R24_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS = r24_APPLICABLE_COUNTERPARTY_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS() {
		return R24_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public void setR24_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS(BigDecimal r24_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS) {
		R24_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS = r24_RISK_WEIGHTED_ASSET_EQUITY_CONTRACTS;
	}
	public BigDecimal getR24_LINE_NO_PRECIOUS_CONTRACTS() {
		return R24_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public void setR24_LINE_NO_PRECIOUS_CONTRACTS(BigDecimal r24_LINE_NO_PRECIOUS_CONTRACTS) {
		R24_LINE_NO_PRECIOUS_CONTRACTS = r24_LINE_NO_PRECIOUS_CONTRACTS;
	}
	public String getR24_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS() {
		return R24_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public void setR24_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS(String r24_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS) {
		R24_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS = r24_RESIDUAL_MATURITY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS() {
		return R24_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public void setR24_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS(BigDecimal r24_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS) {
		R24_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS = r24_PRINCIPAL_AMOUNT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_TOTAL_CURRENT_PRECIOUS_CONTRACTS() {
		return R24_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public void setR24_TOTAL_CURRENT_PRECIOUS_CONTRACTS(BigDecimal r24_TOTAL_CURRENT_PRECIOUS_CONTRACTS) {
		R24_TOTAL_CURRENT_PRECIOUS_CONTRACTS = r24_TOTAL_CURRENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS() {
		return R24_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public void setR24_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS(
			BigDecimal r24_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS) {
		R24_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS = r24_POTENTIAL_FUTURE_CREDIT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS() {
		return R24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public void setR24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS(
			BigDecimal r24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS) {
		R24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS = r24_POTENTIAL_FUTURE_CREDIT_EXPOSURE_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS() {
		return R24_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public void setR24_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS(BigDecimal r24_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS) {
		R24_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS = r24_CREDIT_EQUIVALENT_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS() {
		return R24_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public void setR24_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS(
			BigDecimal r24_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS) {
		R24_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS = r24_APPLICABLE_COUNTERPARTY_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR24_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS() {
		return R24_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public void setR24_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS(BigDecimal r24_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS) {
		R24_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS = r24_RISK_WEIGHTED_ASSET_PRECIOUS_CONTRACTS;
	}
	public BigDecimal getR30_LINE_NO_DEBT_CONTRACTS() {
		return R30_LINE_NO_DEBT_CONTRACTS;
	}
	public void setR30_LINE_NO_DEBT_CONTRACTS(BigDecimal r30_LINE_NO_DEBT_CONTRACTS) {
		R30_LINE_NO_DEBT_CONTRACTS = r30_LINE_NO_DEBT_CONTRACTS;
	}
	public String getR30_RESIDUAL_MATURITY_DEBT_CONTRACTS() {
		return R30_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public void setR30_RESIDUAL_MATURITY_DEBT_CONTRACTS(String r30_RESIDUAL_MATURITY_DEBT_CONTRACTS) {
		R30_RESIDUAL_MATURITY_DEBT_CONTRACTS = r30_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_PRINCIPAL_AMOUNT_DEBT_CONTRACTS() {
		return R30_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public void setR30_PRINCIPAL_AMOUNT_DEBT_CONTRACTS(BigDecimal r30_PRINCIPAL_AMOUNT_DEBT_CONTRACTS) {
		R30_PRINCIPAL_AMOUNT_DEBT_CONTRACTS = r30_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_TOTAL_CURRENT_DEBT_CONTRACTS() {
		return R30_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public void setR30_TOTAL_CURRENT_DEBT_CONTRACTS(BigDecimal r30_TOTAL_CURRENT_DEBT_CONTRACTS) {
		R30_TOTAL_CURRENT_DEBT_CONTRACTS = r30_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS() {
		return R30_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public void setR30_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS(BigDecimal r30_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS) {
		R30_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS = r30_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS() {
		return R30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public void setR30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS(
			BigDecimal r30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS) {
		R30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS = r30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_CREDIT_EQUIVALENT_DEBT_CONTRACTS() {
		return R30_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public void setR30_CREDIT_EQUIVALENT_DEBT_CONTRACTS(BigDecimal r30_CREDIT_EQUIVALENT_DEBT_CONTRACTS) {
		R30_CREDIT_EQUIVALENT_DEBT_CONTRACTS = r30_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS() {
		return R30_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public void setR30_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS(BigDecimal r30_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS) {
		R30_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS = r30_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS() {
		return R30_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public void setR30_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS(BigDecimal r30_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS) {
		R30_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS = r30_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public BigDecimal getR30_LINE_NO_CREDIT_CONTRACTS() {
		return R30_LINE_NO_CREDIT_CONTRACTS;
	}
	public void setR30_LINE_NO_CREDIT_CONTRACTS(BigDecimal r30_LINE_NO_CREDIT_CONTRACTS) {
		R30_LINE_NO_CREDIT_CONTRACTS = r30_LINE_NO_CREDIT_CONTRACTS;
	}
	public String getR30_RESIDUAL_MATURITY_CREDIT_CONTRACTS() {
		return R30_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public void setR30_RESIDUAL_MATURITY_CREDIT_CONTRACTS(String r30_RESIDUAL_MATURITY_CREDIT_CONTRACTS) {
		R30_RESIDUAL_MATURITY_CREDIT_CONTRACTS = r30_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR30_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS() {
		return R30_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public void setR30_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS(BigDecimal r30_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS) {
		R30_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS = r30_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR30_TOTAL_CURRENT_CREDIT_CONTRACTS() {
		return R30_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public void setR30_TOTAL_CURRENT_CREDIT_CONTRACTS(BigDecimal r30_TOTAL_CURRENT_CREDIT_CONTRACTS) {
		R30_TOTAL_CURRENT_CREDIT_CONTRACTS = r30_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR30_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS() {
		return R30_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public void setR30_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS(BigDecimal r30_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS) {
		R30_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS = r30_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS() {
		return R30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public void setR30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS(
			BigDecimal r30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS) {
		R30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS = r30_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public BigDecimal getR30_CREDIT_EQUIVALENT_CREDIT_CONTRACTS() {
		return R30_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public void setR30_CREDIT_EQUIVALENT_CREDIT_CONTRACTS(BigDecimal r30_CREDIT_EQUIVALENT_CREDIT_CONTRACTS) {
		R30_CREDIT_EQUIVALENT_CREDIT_CONTRACTS = r30_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR30_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS() {
		return R30_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public void setR30_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS(BigDecimal r30_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS) {
		R30_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS = r30_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR30_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS() {
		return R30_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public void setR30_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS(BigDecimal r30_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS) {
		R30_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS = r30_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_LINE_NO_DEBT_CONTRACTS() {
		return R31_LINE_NO_DEBT_CONTRACTS;
	}
	public void setR31_LINE_NO_DEBT_CONTRACTS(BigDecimal r31_LINE_NO_DEBT_CONTRACTS) {
		R31_LINE_NO_DEBT_CONTRACTS = r31_LINE_NO_DEBT_CONTRACTS;
	}
	public String getR31_RESIDUAL_MATURITY_DEBT_CONTRACTS() {
		return R31_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public void setR31_RESIDUAL_MATURITY_DEBT_CONTRACTS(String r31_RESIDUAL_MATURITY_DEBT_CONTRACTS) {
		R31_RESIDUAL_MATURITY_DEBT_CONTRACTS = r31_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_PRINCIPAL_AMOUNT_DEBT_CONTRACTS() {
		return R31_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public void setR31_PRINCIPAL_AMOUNT_DEBT_CONTRACTS(BigDecimal r31_PRINCIPAL_AMOUNT_DEBT_CONTRACTS) {
		R31_PRINCIPAL_AMOUNT_DEBT_CONTRACTS = r31_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_TOTAL_CURRENT_DEBT_CONTRACTS() {
		return R31_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public void setR31_TOTAL_CURRENT_DEBT_CONTRACTS(BigDecimal r31_TOTAL_CURRENT_DEBT_CONTRACTS) {
		R31_TOTAL_CURRENT_DEBT_CONTRACTS = r31_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS() {
		return R31_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public void setR31_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS(BigDecimal r31_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS) {
		R31_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS = r31_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS() {
		return R31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public void setR31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS(
			BigDecimal r31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS) {
		R31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS = r31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_CREDIT_EQUIVALENT_DEBT_CONTRACTS() {
		return R31_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public void setR31_CREDIT_EQUIVALENT_DEBT_CONTRACTS(BigDecimal r31_CREDIT_EQUIVALENT_DEBT_CONTRACTS) {
		R31_CREDIT_EQUIVALENT_DEBT_CONTRACTS = r31_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS() {
		return R31_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public void setR31_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS(BigDecimal r31_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS) {
		R31_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS = r31_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS() {
		return R31_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public void setR31_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS(BigDecimal r31_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS) {
		R31_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS = r31_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public BigDecimal getR31_LINE_NO_CREDIT_CONTRACTS() {
		return R31_LINE_NO_CREDIT_CONTRACTS;
	}
	public void setR31_LINE_NO_CREDIT_CONTRACTS(BigDecimal r31_LINE_NO_CREDIT_CONTRACTS) {
		R31_LINE_NO_CREDIT_CONTRACTS = r31_LINE_NO_CREDIT_CONTRACTS;
	}
	public String getR31_RESIDUAL_MATURITY_CREDIT_CONTRACTS() {
		return R31_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public void setR31_RESIDUAL_MATURITY_CREDIT_CONTRACTS(String r31_RESIDUAL_MATURITY_CREDIT_CONTRACTS) {
		R31_RESIDUAL_MATURITY_CREDIT_CONTRACTS = r31_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS() {
		return R31_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public void setR31_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS(BigDecimal r31_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS) {
		R31_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS = r31_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_TOTAL_CURRENT_CREDIT_CONTRACTS() {
		return R31_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public void setR31_TOTAL_CURRENT_CREDIT_CONTRACTS(BigDecimal r31_TOTAL_CURRENT_CREDIT_CONTRACTS) {
		R31_TOTAL_CURRENT_CREDIT_CONTRACTS = r31_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS() {
		return R31_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public void setR31_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS(BigDecimal r31_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS) {
		R31_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS = r31_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS() {
		return R31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public void setR31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS(
			BigDecimal r31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS) {
		R31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS = r31_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_CREDIT_EQUIVALENT_CREDIT_CONTRACTS() {
		return R31_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public void setR31_CREDIT_EQUIVALENT_CREDIT_CONTRACTS(BigDecimal r31_CREDIT_EQUIVALENT_CREDIT_CONTRACTS) {
		R31_CREDIT_EQUIVALENT_CREDIT_CONTRACTS = r31_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS() {
		return R31_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public void setR31_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS(BigDecimal r31_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS) {
		R31_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS = r31_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR31_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS() {
		return R31_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public void setR31_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS(BigDecimal r31_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS) {
		R31_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS = r31_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_LINE_NO_DEBT_CONTRACTS() {
		return R32_LINE_NO_DEBT_CONTRACTS;
	}
	public void setR32_LINE_NO_DEBT_CONTRACTS(BigDecimal r32_LINE_NO_DEBT_CONTRACTS) {
		R32_LINE_NO_DEBT_CONTRACTS = r32_LINE_NO_DEBT_CONTRACTS;
	}
	public String getR32_RESIDUAL_MATURITY_DEBT_CONTRACTS() {
		return R32_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public void setR32_RESIDUAL_MATURITY_DEBT_CONTRACTS(String r32_RESIDUAL_MATURITY_DEBT_CONTRACTS) {
		R32_RESIDUAL_MATURITY_DEBT_CONTRACTS = r32_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_PRINCIPAL_AMOUNT_DEBT_CONTRACTS() {
		return R32_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public void setR32_PRINCIPAL_AMOUNT_DEBT_CONTRACTS(BigDecimal r32_PRINCIPAL_AMOUNT_DEBT_CONTRACTS) {
		R32_PRINCIPAL_AMOUNT_DEBT_CONTRACTS = r32_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_TOTAL_CURRENT_DEBT_CONTRACTS() {
		return R32_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public void setR32_TOTAL_CURRENT_DEBT_CONTRACTS(BigDecimal r32_TOTAL_CURRENT_DEBT_CONTRACTS) {
		R32_TOTAL_CURRENT_DEBT_CONTRACTS = r32_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS() {
		return R32_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public void setR32_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS(BigDecimal r32_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS) {
		R32_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS = r32_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS() {
		return R32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public void setR32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS(
			BigDecimal r32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS) {
		R32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS = r32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_CREDIT_EQUIVALENT_DEBT_CONTRACTS() {
		return R32_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public void setR32_CREDIT_EQUIVALENT_DEBT_CONTRACTS(BigDecimal r32_CREDIT_EQUIVALENT_DEBT_CONTRACTS) {
		R32_CREDIT_EQUIVALENT_DEBT_CONTRACTS = r32_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS() {
		return R32_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public void setR32_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS(BigDecimal r32_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS) {
		R32_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS = r32_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS() {
		return R32_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public void setR32_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS(BigDecimal r32_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS) {
		R32_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS = r32_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public BigDecimal getR32_LINE_NO_CREDIT_CONTRACTS() {
		return R32_LINE_NO_CREDIT_CONTRACTS;
	}
	public void setR32_LINE_NO_CREDIT_CONTRACTS(BigDecimal r32_LINE_NO_CREDIT_CONTRACTS) {
		R32_LINE_NO_CREDIT_CONTRACTS = r32_LINE_NO_CREDIT_CONTRACTS;
	}
	public String getR32_RESIDUAL_MATURITY_CREDIT_CONTRACTS() {
		return R32_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public void setR32_RESIDUAL_MATURITY_CREDIT_CONTRACTS(String r32_RESIDUAL_MATURITY_CREDIT_CONTRACTS) {
		R32_RESIDUAL_MATURITY_CREDIT_CONTRACTS = r32_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS() {
		return R32_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public void setR32_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS(BigDecimal r32_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS) {
		R32_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS = r32_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_TOTAL_CURRENT_CREDIT_CONTRACTS() {
		return R32_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public void setR32_TOTAL_CURRENT_CREDIT_CONTRACTS(BigDecimal r32_TOTAL_CURRENT_CREDIT_CONTRACTS) {
		R32_TOTAL_CURRENT_CREDIT_CONTRACTS = r32_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS() {
		return R32_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public void setR32_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS(BigDecimal r32_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS) {
		R32_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS = r32_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS() {
		return R32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public void setR32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS(
			BigDecimal r32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS) {
		R32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS = r32_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_CREDIT_EQUIVALENT_CREDIT_CONTRACTS() {
		return R32_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public void setR32_CREDIT_EQUIVALENT_CREDIT_CONTRACTS(BigDecimal r32_CREDIT_EQUIVALENT_CREDIT_CONTRACTS) {
		R32_CREDIT_EQUIVALENT_CREDIT_CONTRACTS = r32_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS() {
		return R32_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public void setR32_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS(BigDecimal r32_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS) {
		R32_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS = r32_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR32_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS() {
		return R32_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public void setR32_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS(BigDecimal r32_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS) {
		R32_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS = r32_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_LINE_NO_DEBT_CONTRACTS() {
		return R33_LINE_NO_DEBT_CONTRACTS;
	}
	public void setR33_LINE_NO_DEBT_CONTRACTS(BigDecimal r33_LINE_NO_DEBT_CONTRACTS) {
		R33_LINE_NO_DEBT_CONTRACTS = r33_LINE_NO_DEBT_CONTRACTS;
	}
	public String getR33_RESIDUAL_MATURITY_DEBT_CONTRACTS() {
		return R33_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public void setR33_RESIDUAL_MATURITY_DEBT_CONTRACTS(String r33_RESIDUAL_MATURITY_DEBT_CONTRACTS) {
		R33_RESIDUAL_MATURITY_DEBT_CONTRACTS = r33_RESIDUAL_MATURITY_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_PRINCIPAL_AMOUNT_DEBT_CONTRACTS() {
		return R33_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public void setR33_PRINCIPAL_AMOUNT_DEBT_CONTRACTS(BigDecimal r33_PRINCIPAL_AMOUNT_DEBT_CONTRACTS) {
		R33_PRINCIPAL_AMOUNT_DEBT_CONTRACTS = r33_PRINCIPAL_AMOUNT_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_TOTAL_CURRENT_DEBT_CONTRACTS() {
		return R33_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public void setR33_TOTAL_CURRENT_DEBT_CONTRACTS(BigDecimal r33_TOTAL_CURRENT_DEBT_CONTRACTS) {
		R33_TOTAL_CURRENT_DEBT_CONTRACTS = r33_TOTAL_CURRENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS() {
		return R33_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public void setR33_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS(BigDecimal r33_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS) {
		R33_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS = r33_POTENTIAL_FUTURE_CREDIT_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS() {
		return R33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public void setR33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS(
			BigDecimal r33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS) {
		R33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS = r33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_CREDIT_EQUIVALENT_DEBT_CONTRACTS() {
		return R33_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public void setR33_CREDIT_EQUIVALENT_DEBT_CONTRACTS(BigDecimal r33_CREDIT_EQUIVALENT_DEBT_CONTRACTS) {
		R33_CREDIT_EQUIVALENT_DEBT_CONTRACTS = r33_CREDIT_EQUIVALENT_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS() {
		return R33_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public void setR33_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS(BigDecimal r33_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS) {
		R33_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS = r33_APPLICABLE_COUNTERPARTY_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS() {
		return R33_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public void setR33_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS(BigDecimal r33_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS) {
		R33_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS = r33_RISK_WEIGHTED_ASSET_DEBT_CONTRACTS;
	}
	public BigDecimal getR33_LINE_NO_CREDIT_CONTRACTS() {
		return R33_LINE_NO_CREDIT_CONTRACTS;
	}
	public void setR33_LINE_NO_CREDIT_CONTRACTS(BigDecimal r33_LINE_NO_CREDIT_CONTRACTS) {
		R33_LINE_NO_CREDIT_CONTRACTS = r33_LINE_NO_CREDIT_CONTRACTS;
	}
	public String getR33_RESIDUAL_MATURITY_CREDIT_CONTRACTS() {
		return R33_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public void setR33_RESIDUAL_MATURITY_CREDIT_CONTRACTS(String r33_RESIDUAL_MATURITY_CREDIT_CONTRACTS) {
		R33_RESIDUAL_MATURITY_CREDIT_CONTRACTS = r33_RESIDUAL_MATURITY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS() {
		return R33_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public void setR33_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS(BigDecimal r33_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS) {
		R33_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS = r33_PRINCIPAL_AMOUNT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_TOTAL_CURRENT_CREDIT_CONTRACTS() {
		return R33_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public void setR33_TOTAL_CURRENT_CREDIT_CONTRACTS(BigDecimal r33_TOTAL_CURRENT_CREDIT_CONTRACTS) {
		R33_TOTAL_CURRENT_CREDIT_CONTRACTS = r33_TOTAL_CURRENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS() {
		return R33_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public void setR33_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS(BigDecimal r33_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS) {
		R33_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS = r33_POTENTIAL_FUTURE_CREDIT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS() {
		return R33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public void setR33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS(
			BigDecimal r33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS) {
		R33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS = r33_POTENTIAL_FUTURE_CREDIT_EXPOSURE_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_CREDIT_EQUIVALENT_CREDIT_CONTRACTS() {
		return R33_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public void setR33_CREDIT_EQUIVALENT_CREDIT_CONTRACTS(BigDecimal r33_CREDIT_EQUIVALENT_CREDIT_CONTRACTS) {
		R33_CREDIT_EQUIVALENT_CREDIT_CONTRACTS = r33_CREDIT_EQUIVALENT_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS() {
		return R33_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public void setR33_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS(BigDecimal r33_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS) {
		R33_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS = r33_APPLICABLE_COUNTERPARTY_CREDIT_CONTRACTS;
	}
	public BigDecimal getR33_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS() {
		return R33_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public void setR33_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS(BigDecimal r33_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS) {
		R33_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS = r33_RISK_WEIGHTED_ASSET_CREDIT_CONTRACTS;
	}
	public BigDecimal getR43_LINE_NO_DERIVATIVE_CONTRACTS() {
		return R43_LINE_NO_DERIVATIVE_CONTRACTS;
	}
	public void setR43_LINE_NO_DERIVATIVE_CONTRACTS(BigDecimal r43_LINE_NO_DERIVATIVE_CONTRACTS) {
		R43_LINE_NO_DERIVATIVE_CONTRACTS = r43_LINE_NO_DERIVATIVE_CONTRACTS;
	}
	public String getR43_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS() {
		return R43_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
	}
	public void setR43_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS(String r43_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS) {
		R43_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS = r43_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR43_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS() {
		return R43_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
	}
	public void setR43_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS(BigDecimal r43_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS) {
		R43_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS = r43_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR43_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS() {
		return R43_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
	}
	public void setR43_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS(
			BigDecimal r43_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS) {
		R43_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS = r43_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR43_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS() {
		return R43_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
	}
	public void setR43_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS(BigDecimal r43_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS) {
		R43_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS = r43_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR43_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS() {
		return R43_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
	}
	public void setR43_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS(BigDecimal r43_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS) {
		R43_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS = r43_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR43_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS() {
		return R43_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
	}
	public void setR43_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS(
			BigDecimal r43_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS) {
		R43_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS = r43_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR43_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS() {
		return R43_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
	}
	public void setR43_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS(BigDecimal r43_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS) {
		R43_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS = r43_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR44_LINE_NO_DERIVATIVE_CONTRACTS() {
		return R44_LINE_NO_DERIVATIVE_CONTRACTS;
	}
	public void setR44_LINE_NO_DERIVATIVE_CONTRACTS(BigDecimal r44_LINE_NO_DERIVATIVE_CONTRACTS) {
		R44_LINE_NO_DERIVATIVE_CONTRACTS = r44_LINE_NO_DERIVATIVE_CONTRACTS;
	}
	public String getR44_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS() {
		return R44_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
	}
	public void setR44_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS(String r44_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS) {
		R44_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS = r44_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR44_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS() {
		return R44_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
	}
	public void setR44_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS(BigDecimal r44_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS) {
		R44_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS = r44_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR44_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS() {
		return R44_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
	}
	public void setR44_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS(
			BigDecimal r44_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS) {
		R44_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS = r44_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR44_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS() {
		return R44_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
	}
	public void setR44_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS(BigDecimal r44_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS) {
		R44_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS = r44_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR44_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS() {
		return R44_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
	}
	public void setR44_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS(BigDecimal r44_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS) {
		R44_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS = r44_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR44_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS() {
		return R44_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
	}
	public void setR44_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS(
			BigDecimal r44_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS) {
		R44_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS = r44_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR44_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS() {
		return R44_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
	}
	public void setR44_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS(BigDecimal r44_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS) {
		R44_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS = r44_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR45_LINE_NO_DERIVATIVE_CONTRACTS() {
		return R45_LINE_NO_DERIVATIVE_CONTRACTS;
	}
	public void setR45_LINE_NO_DERIVATIVE_CONTRACTS(BigDecimal r45_LINE_NO_DERIVATIVE_CONTRACTS) {
		R45_LINE_NO_DERIVATIVE_CONTRACTS = r45_LINE_NO_DERIVATIVE_CONTRACTS;
	}
	public String getR45_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS() {
		return R45_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
	}
	public void setR45_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS(String r45_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS) {
		R45_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS = r45_NETTED_EXPOSURES_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR45_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS() {
		return R45_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
	}
	public void setR45_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS(BigDecimal r45_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS) {
		R45_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS = r45_PRINCIPAL_AMOUNT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR45_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS() {
		return R45_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
	}
	public void setR45_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS(
			BigDecimal r45_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS) {
		R45_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS = r45_POSITIVE_NET_REPLACEMENT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR45_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS() {
		return R45_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
	}
	public void setR45_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS(BigDecimal r45_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS) {
		R45_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS = r45_ADDON_FOR_NETTED_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR45_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS() {
		return R45_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
	}
	public void setR45_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS(BigDecimal r45_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS) {
		R45_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS = r45_CREDIT_EQUIVALENT_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR45_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS() {
		return R45_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
	}
	public void setR45_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS(
			BigDecimal r45_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS) {
		R45_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS = r45_APPLICABLE_COUNTERPARTY_DERIVATIVE_CONTRACTS;
	}
	public BigDecimal getR45_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS() {
		return R45_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
	}
	public void setR45_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS(BigDecimal r45_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS) {
		R45_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS = r45_RISK_WEIGHTED_ASSET_DERIVATIVE_CONTRACTS;
	}
	public Date getReport_date() {
		return report_date;
	}
	public void setReport_date(Date report_date) {
		this.report_date = report_date;
	}
	public BigDecimal getReport_version() {
		return report_version;
	}
	public void setReport_version(BigDecimal report_version) {
		this.report_version = report_version;
	}
	public String getReport_frequency() {
		return report_frequency;
	}
	public void setReport_frequency(String report_frequency) {
		this.report_frequency = report_frequency;
	}
	public String getReport_code() {
		return report_code;
	}
	public void setReport_code(String report_code) {
		this.report_code = report_code;
	}
	public String getReport_desc() {
		return report_desc;
	}
	public void setReport_desc(String report_desc) {
		this.report_desc = report_desc;
	}
	public String getEntity_flg() {
		return entity_flg;
	}
	public void setEntity_flg(String entity_flg) {
		this.entity_flg = entity_flg;
	}
	public String getModify_flg() {
		return modify_flg;
	}
	public void setModify_flg(String modify_flg) {
		this.modify_flg = modify_flg;
	}
	public String getDel_flg() {
		return del_flg;
	}
	public void setDel_flg(String del_flg) {
		this.del_flg = del_flg;
	}
	public M_SRWA_12D_Detail_Entity() {
		super();
		// TODO Auto-generated constructor stub
	}
}
